---
- repo: local
  hooks:
    - id: yamllint
      name: yamllint
      entry: yamllint -c .github/yamllint.cfg .
      language: python_venv
      types: [file, yaml]
    - id: automated-docs
      name: auto-documentation-automations
      entry: python3 scripts/auto-documentation-automations.py
      language: python_venv
      verbose: true
