- id: '1655302783520'
  alias: 'Doorbell: button pressed'
  description: ''
  trigger:
  - type: connected
    platform: device
    device_id: 498618c4bb775b9d0a1963689f168ddb
    entity_id: binary_sensor.a8105_e_0_call_button
    domain: binary_sensor
  condition: []
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.kitchen
    data:
      media_content_id: media-source://tts/google_translate?message=ding+dong+-+somebody+is+at+the+door
      media_content_type: provider
    metadata:
      title: ding dong - somebody is at the door
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=ding+dong+-+somebody+is+at+the+door
  - service: media_player.play_media
    target:
      entity_id: media_player.office
    data:
      media_content_id: media-source://tts/google_translate?message=ding+dong+-+somebody+is+at+the+door
      media_content_type: provider
    metadata:
      title: ding dong - somebody is at the door
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=ding+dong+-+somebody+is+at+the+door
  - service: notify.telegram_jon
    data:
      message: doorbell just rang
      title: Doorbell!
  mode: single
