---
###################################
# mjpeg cameras
- platform: mjpeg
  mjpeg_url: http://192.168.46.112:80/Streaming/Channels/2/preview
  name: Deck
  username: admin
  password: !secret hik_pwd
- platform: mjpeg
  mjpeg_url: http://192.168.46.113:80/Streaming/Channels/2/preview
  name: Deck Stairs
  username: admin
  password: !secret hik_pwd
- platform: mjpeg
  mjpeg_url: http://192.168.46.116:80/Streaming/Channels/2/preview
  name: Front Door
  username: admin
  password: !secret hik_pwd
- platform: mjpeg
  mjpeg_url: http://192.168.46.110:80/Streaming/Channels/2/preview
  name: Driveway
  username: admin
  password: !secret hik_pwd
- platform: mjpeg
  mjpeg_url: http://192.168.46.111:80/Streaming/Channels/2/preview
  name: Daisy
  username: admin
  password: !secret hik_pwd
- platform: mjpeg
  mjpeg_url: http://192.168.46.115:80/Streaming/Channels/2/preview
  name: Garage
  username: admin
  password: !secret hik_pwd

###################################
- platform: ffmpeg
  name: Kitchen Camera
  input: !secret kitchenwyze_cam
- platform: ffmpeg
  name: Patio
  input: !secret patio_cam

###################################
# still image cameras
- name: Deck Last Person
  platform: mqtt
  topic: frigate/deck/person/snapshot
- name: Driveway Last Person
  platform: mqtt
  topic: frigate/driveway/person/snapshot
- name: Doorbell Last Person
  platform: mqtt
  topic: frigate/doorbell/person/snapshot
- name: Garage Last Person
  platform: mqtt
  topic: frigate/garage/person/snapshot
- name: Deck Stairs Last Person
  platform: mqtt
  topic: frigate/deck_stairs/person/snapshot
