---
default_config:
homeassistant:
  name: !secret name
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  currency: USD
  country: US
  time_zone: !secret ha_tz
  external_url: !secret ext_hass_url
  internal_url: !secret int_hass_url
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - "/tmp"
    - "/config/www"
    - "/share"
  media_dirs:
    local: /media
cloud:
energy:
datadog:
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.30.0/24
    - 192.168.31.0/24
  login_attempts_threshold: 3
  ip_ban_enabled: false
tts:
  - platform: google_translate
    service_name: google_say
recorder:
  db_url: !secret url_db
  purge_keep_days: 21
  exclude:
    entity_globs:
      - sensor.sensor.tomorrow_io*
      - sensor.pixel*
frontend:
  themes: !include_dir_merge_named themes/
lovelace:
  mode: yaml
  dashboards:
    wallpanel-dashboard:
      mode: yaml
      title: Wallpanel
      icon: mdi:time
      show_in_sidebar: true
      filename: wallpanel.yaml
system_health:

# influxdb:
#   host: localhost
#   username: !secret influx_usr
#   password: !secret influx_pwd
#   database: !secret influx_db
#   include:
#     domains:
#       - sensor
#       - binary_sensor
#       - climate
#       - device_tracker
#       - lock
#     entities:
#       - switch.basement_equipment_room_recirculation_pump
#       - switch.water_main_shut_off

elkm1:
  host: !secret url_elk
  area:
    exclude: [2-8]
  zone:
    exclude: [33-208]
  output:
    exclude: [1-208]
  counter:
    exclude: [2-64]
  keypad:
    include: [1-3]
  task:
    enabled: false
  thermostat:
    enabled: false
  plc:
    enabled: false
  setting:
    enabled: false

lutron_caseta:
  - host: !secret ra3_ip
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

notify:
  - name: telegram_jon
    platform: telegram
    chat_id: !secret telegram_chat

telegram_bot:
  - platform: polling
    parse_mode: html
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat

####################################################
#                     Includes                     #
####################################################
adaptive_lighting: !include includes/adaptive_lighting.yaml
alert: !include includes/alerts.yaml
automation: !include automations.yaml
automation yaml: !include_dir_merge_list automation
binary_sensor: !include includes/binary_sensors.yaml
camera: !include includes/cameras.yaml
climate: !include includes/climate.yaml
cover: !include includes/covers.yaml
device_tracker: !include includes/device_tracker.yaml
# fan: !include includes/fans.yaml
group: !include includes/groups.yaml
input_boolean: !include includes/input_booleans.yaml
input_select: !include includes/input_selects.yaml
intent_script: !include includes/intent_scripts.yaml
proximity: !include includes/proximity.yaml
rest_command: !include includes/rest_commands.yaml
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
shell_command: !include includes/shell_commands.yaml
switch: !include includes/switches.yaml
template: !include includes/template.yaml
zone: !include includes/zones.yaml

logger:
  default: error
  logs:
    custom_components.localtuya.common: fatal
    # homeassistant.components.lutron_caseta: debug
    # pylutron_caseta: debug

panel_custom:
  - name: panel_supervisor
    sidebar_title: Supervisor Add-ons
    sidebar_icon: mdi:home-assistant
    url_path: hassio/dashboard
    module_url: /api/hassio/app/entrypoint.js
    embed_iframe: true
    require_admin: true

history:
websocket_api:
sun:
conversation:
logbook:
person:
config:
hassio:
map:
mobile_app:
media_source:

speedtestdotnet:
  scan_interval:
    minutes: 121
