---
default_config:
homeassistant:
  name: !secret name
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  currency: USD
  country: US
  time_zone: !secret ha_tz
  external_url: !secret ext_hass_url
  internal_url: !secret int_hass_url
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - "/tmp"
    - "/config/www"
  media_dirs:
    local: /media
cloud:
energy:
datadog:
  host: 192.168.30.243

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.0/24
    - 192.168.30.0/24
    - 192.168.31.0/24
  login_attempts_threshold: 3
  ip_ban_enabled: false
tts:
  - platform: google_translate
    service_name: google_say
frontend:
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
lovelace:
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
    - url: /hacsfiles/custom-sonos-card/custom-sonos-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: https://fonts.googleapis.com/css2?family=Antonio:wght@400;700&display=swap
      type: css
    - url: https://cdn.jsdelivr.net/gh/th3jesta/ha-lcars@js-main/lcars.js
      type: js
system_health:

elkm1:
  host: !secret url_elk
  area:
    exclude: [2-8]
  zone:
    exclude: [33-208]
  output:
    exclude: [1-208]
  counter:
    exclude: [2-64]
  keypad:
    include: [1-3]
  task:
    enabled: false
  thermostat:
    enabled: false
  plc:
    enabled: false
  setting:
    enabled: false

lutron_caseta:
  - host: !secret ra3_ip
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

notify:
  - name: telegram_jon
    platform: telegram
    chat_id: !secret telegram_chat

telegram_bot:
  - platform: polling
    parse_mode: html
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat

calendar:
  - platform: todoist
    token: !secret todoist

####################################################
#                     Includes                     #
####################################################
adaptive_lighting: !include includes/adaptive_lighting.yaml
alert: !include includes/alerts.yaml
automation: !include automations.yaml
automation yaml: !include automation.yaml
camera: !include includes/cameras.yaml
cover: !include includes/covers.yaml
group: !include includes/groups.yaml
input_boolean: !include includes/input_booleans.yaml
input_select: !include includes/input_selects.yaml
input_text: !include includes/input_text.yaml
input_number: !include includes/input_number.yaml
intent_script: !include includes/intent_scripts.yaml
light: !include includes/lights.yaml
mqtt: !include includes/mqtt.yaml
rest_command: !include includes/rest_commands.yaml
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
shell_command: !include includes/shell_commands.yaml
switch: !include includes/switches.yaml
template: !include includes/template.yaml
zone: !include includes/zones.yaml

logger:
  default: error

history:
websocket_api:
sun:
conversation:
logbook:
person:
config:
mobile_app:
media_source:
wake_on_lan:

# weather:
#   - platform: template
#     name: Local Weather
#     condition_template: "{{ states('sensor.hub_hb_00069559_weather') }}"
#     temperature_template: "{{ states('sensor.weatherflow_tempest_temperature') | float}}"
#     humidity_template: "{{ states('sensor.weatherflow_tempest_humidity')| int }}"
#     pressure_template: "{{ states('sensor.weatherflow_tempest_sea_level_pressure')| float }}"
#     wind_speed_template: "{{ states('sensor.weatherflow_tempest_wind_speed_avg')| float }}"
#     wind_bearing_template: "{{ states('sensor.weatherflow_tempest_wind_bearing_avg')| int }}"
#     visibility_template: "{{ states('sensor.weatherflow_tempest_visibility')| float }}"
#     forecast_hourly_template: >-
#       {% set data = namespace(l = []) %}
#       {% for e in state_attr('sensor.hub_hb_00069559_weather', 'hourly_forecast') %}
#       {%   set data.l = data.l + [ {
#               'datetime': e.datetime,
#               'condition': e.condition,
#               'temperature': e.temperature,
#               'native_apparent_temperature': e.feels_like,
#               'pressure': e.pressure,
#               'humidity': e.humidity,
#               'precipitation': e.precipitation,
#               'precipitation_probability': e.precipitation_probability,
#               'wind_speed': e.wind_speed,
#               'native_wind_gust_speed': e.wind_gust,
#               'wind_bearing': e.wind_bearing,
#               'uv_index': e.uv
#             } ] %}
#       {% endfor %}
#       {{ data.l }}
#     forecast_daily_template: >-
#       {% set data = namespace(l = []) %}
#       {% for e in state_attr('sensor.hub_hb_00069559_weather', 'daily_forecast') %}
#       {%   set data.l = data.l + [ {
#               'datetime': e.datetime,
#               'condition': e.condition,
#               'temperature': e.temperature,
#               'templow': e.templow,
#               'precipitation': e.precipitation,
#               'precipitation_probability': e.precipitation_probability,
#               'wind_speed': e.wind_speed,
#               'wind_bearing': e.wind_bearing
#             } ] %}
#       {% endfor %}
#       {{ data.l }}

homekit:
  - filter:
      include_entities:
        - binary_sensor.elkm1_kitchen_pir
        - binary_sensor.elkm1_foyer_pir
        - cover.single_garage_door
        - cover.double_garage_door

sonos:
  media_player:
    advertise_addr: 192.168.30.249
    hosts:
      - 192.168.30.38
      - 192.168.30.39
      - 192.168.30.40
      - 192.168.30.41
      - 192.168.30.42
      - 192.168.30.43
      - 192.168.30.44
      - 192.168.30.45
      - 192.168.30.46
      - 192.168.30.47
      - 192.168.30.48
      - 192.168.30.49
      - 192.168.30.51
      - 192.168.30.52
      - 192.168.30.53
