---
homeassistant:
  name: !secret name
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: !secret ha_tz
  customize: !include customize.yaml
  allowlist_external_dirs:
    - "/tmp"
    - "/config/www"
    - "/share"
  packages: !include_dir_named packages
  media_dirs:
    local: /media

http:
  base_url: !secret hass_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
updater:
  reporting: false
tts:
  - platform: google_translate
    service_name: google_say
recorder:
  db_url: !secret url_db
  purge_keep_days: 21
  exclude:
    entity_globs:
      - sensor.dark_sky*

system_health:
circadian_lighting:
  min_colortemp: 2700
  max_colortemp: 5200
  sunrise_offset: 01:00:00
  interval: 420
  # sunset_offset:

influxdb:
  host: localhost
  username: !secret influx_usr
  password: !secret influx_pwd
  database: !secret influx_db
  include:
    domains:
      - sensor
      - binary_sensor
      - climate
      - device_tracker
      - lock
    entities:
      - switch.equipment_room_recirculation_pump
      - switch.water_main_shut_off

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

elkm1:
  host: !secret url_elk
  area:
    exclude: [2-8]
  zone:
    exclude: [17-24, 29-32, 41-208]
  output:
    exclude: [1-8, 11-208]
  counter:
    exclude: [2-64]
  keypad:
    include: [1-5]
  task:
    include: [1-4]
  thermostat:
    enabled: false
  plc:
    enabled: false
  setting:
    enabled: false

# hass_opensprinkler:
#   host: !secret os_host
#   password: !secret os_passwd

# sleepiq:
#   username: !secret sleep_usr
#   password: !secret sleep_pwd

# nest:
#   client_id: !secret nest_client_id
#   client_secret: !secret nest_client_secret
#   project_id: !secret nest_project_id
#   subscriber_id: !secret nest_subscriber_id

lutron:
  host: !secret rr_ip
  username: !secret rr_usr
  password: !secret rr_pwd

# water_heater:
#   - platform: econet
#     username: !secret econet_user
#     password: !secret econet_pwd

hunterdouglas_powerview:
  - host: !secret powerview_ip

notify:
  - name: telegram_jon
    platform: telegram
    chat_id: !secret telegram_chat

telegram_bot:
  - platform: polling
    parse_mode: html
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat

####################################################
#                     Includes                     #
####################################################
alert: !include includes/alerts.yaml
automation: !include_dir_merge_list automation
binary_sensor: !include includes/binary_sensors.yaml
camera: !include includes/cameras.yaml
climate: !include includes/climate.yaml
cover: !include includes/covers.yaml
fan: !include includes/fans.yaml
group: !include includes/groups.yaml
input_boolean: !include includes/input_booleans.yaml
input_select: !include includes/input_selects.yaml
intent_script: !include includes/intent_scripts.yaml
rest_command: !include includes/rest_commands.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
shell_command: !include includes/shell_commands.yaml
switch: !include includes/switches.yaml
timer: !include includes/timers.yaml
zone: !include includes/zones.yaml

logger:
  default: error

history:
sun:
conversation:
logbook:
# stream:
hacs:
  token: !secret hacs

person:
config:
hassio:
map:
discovery:
  ignore:
    - axis
    - homekit

speedtestdotnet:
  scan_interval:
    minutes: 121

webostv:
  - host: !secret lg_living_room
    name: Living Room TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "a8:23:fe:0c:92:af"
    customize:
      sources:
        - youtubetv
        - netflix

mobile_app:

browser_mod:
  devices:
    37a201ed-e63fb778:
      name: wallpanel
    49d6a277-0090e2cd:
      name: chrome-mac

lifx:
  light:
    - broadcast: 192.168.45.181
    - broadcast: 192.168.45.182
    - broadcast: 192.168.45.183
    - broadcast: 192.168.45.184

folder_watcher:
  - folder: /share
    patterns:
      - "*.mp4"

sonos:
  media_player:
    hosts:
      - 192.168.45.140
      - 192.168.45.141
      - 192.168.45.142
      - 192.168.45.143
      - 192.168.45.144
      - 192.168.45.145
      - 192.168.45.146
      - 192.168.45.147
      - 192.168.45.148
      - 192.168.45.149
media_source:

cast:
  media_player:
    - host: 192.168.45.45

# localtuya:
#   - host: !secret sylvania1_ip
#     device_id: !secret sylvania1_devid
#     local_key: !secret sylvania1_local_key
#     friendly_name: sylvania1
#     protocol_version: "3.3"
#     entities:
#       - platform: light
#         friendly_name: sylvania1
#         id: 20
#         color_mode: 21
#         brightness: 22
#         color_temp: 23
#         color: 24
#         brightness_lower: 10
#         brightness_upper: 1000
#         color_temp_min_kelvin: 2700
#         color_temp_max_kelvin: 6500
#         scene: 25
#   - host: !secret sylvania2_ip
#     device_id: !secret sylvania2_devid
#     local_key: !secret sylvania2_local_key
#     friendly_name: sylvania2
#     protocol_version: "3.3"
#     entities:
#       - platform: light
#         friendly_name: sylvania2
#         id: 20
#         color_mode: 21
#         brightness: 22
#         color_temp: 23
#         color: 24
#         brightness_lower: 10
#         brightness_upper: 1000
#         color_temp_min_kelvin: 2700
#         color_temp_max_kelvin: 6500
#         scene: 25
#   - host: !secret sylvania3_ip
#     device_id: !secret sylvania3_devid
#     local_key: !secret sylvania3_local_key
#     friendly_name: sylvania3
#     protocol_version: "3.3"
#     entities:
#       - platform: light
#         friendly_name: sylvania3
#         id: 20
#         color_mode: 21
#         brightness: 22
#         color_temp: 23
#         color: 24
#         brightness_lower: 10
#         brightness_upper: 1000
#         color_temp_min_kelvin: 2700
#         color_temp_max_kelvin: 6500
#         scene: 25
