---
homeassistant:
  name: !secret name
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: !secret ha_tz
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp
    - /config/www
  packages: !include_dir_named packages

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
updater:
  reporting: false
tts:
  - platform: google_translate
    service_name: google_say
recorder:
  db_url: !secret url_db
  purge_keep_days: 32
  purge_interval: 32

system_health:
circadian_lighting:
  min_colortemp: 2700

influxdb:
  host: localhost
  username: !secret influx_usr
  password: !secret influx_pwd
  database: !secret influx_db
  include:
    domains:
      - sensor
      - binary_sensor
      - climate
      - device_tracker
      - lock
    entities:
      - switch.equipment_room_recirculation_pump
      - switch.water_main_shut_off

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

elkm1:
  host: !secret url_elk
  area:
    exclude: [2-8]
  zone:
    exclude: [17-24, 29-32, 41-208]
  output:
    exclude: [1-8, 11-208]
  counter:
    exclude: [2-64]
  keypad:
    include: [1-5]
  task:
    include: [1-4]
  thermostat:
    enabled: false
  plc:
    enabled: false
  setting:
    enabled: false

# hass_opensprinkler:
#   host: !secret os_host
#   password: !secret os_passwd

sleepiq:
  username: !secret sleep_usr
  password: !secret sleep_pwd

lutron:
  host: !secret rr_ip
  username: !secret rr_usr
  password: !secret rr_pwd

# water_heater:
#   - platform: econet
#     username: !secret econet_user
#     password: !secret econet_pwd

scene:
  platform: hunterdouglas_powerview
  address: !secret powerview_ip

notify:
  - name: telegram_jon
    platform: telegram
    chat_id: !secret telegram_chat

telegram_bot:
  - platform: polling
    parse_mode: html
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat

####################################################
#                     Includes                     #
####################################################
alert: !include alerts.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
climate: !include climate.yaml
automation: !include_dir_merge_list automation
group: !include groups.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
switch: !include switches.yaml
cover: !include covers.yaml
camera: !include cameras.yaml
rest_command: !include rest_commands.yaml
input_boolean: !include input_boolean.yaml
timer: !include timers.yaml
zone: !include zones.yaml

logger:
  default: error

history:
sun:
conversation:
logbook:
frontend:
  themes: !include_dir_merge_named themes/

hacs:
  token: !secret hacs

person:
lovelace:
  mode: yaml
config:
hassio:
map:
discovery:
  ignore:
    - axis
    - igd
    - homekit

speedtestdotnet:
  scan_interval:
    minutes: 121

webostv:
  - host: !secret lg_living_room
    name: Living Room TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "a8:23:fe:0c:92:af"
    customize:
      sources:
        - youtubetv
        - netflix

mobile_app:

browser_mod:
  devices:
    37a201ed-e63fb778:
      name: wallpanel
    4ef21a5e-67e6ec16:
      name: chrome-mac

device_tracker:
  - platform: mqtt
    devices:
      jon_st: "device_tracker/jon/state"

lifx:
  light:
    - broadcast: 192.168.46.181
    - broadcast: 192.168.46.182
    - broadcast: 192.168.46.183
