---
default_config:
homeassistant:
  name: !secret name
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  currency: USD
  country: US
  time_zone: !secret ha_tz
  external_url: !secret ext_hass_url
  internal_url: !secret int_hass_url
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - "/config/www"
  media_dirs:
    local: /media
cloud:
energy:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.0/24
    - 192.168.30.0/24
    - 192.168.31.0/24
  login_attempts_threshold: 3
  ip_ban_enabled: false
tts:
  - platform: google_translate
    service_name: google_say
frontend:
  themes: !include_dir_merge_named themes/

system_health:

elkm1:
  host: !secret url_elk
  area:
    exclude: [2-8]
  zone:
    exclude: [33-208]
  output:
    exclude: [1-208]
  counter:
    exclude: [2-64]
  keypad:
    include: [1-3]
  task:
    enabled: false
  thermostat:
    enabled: false
  plc:
    enabled: false
  setting:
    enabled: false

lutron_caseta:
  - host: !secret ra3_ip
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

calendar:
  - platform: todoist
    token: !secret todoist

####################################################
#                     Includes                     #
####################################################
adaptive_lighting: !include includes/adaptive_lighting.yaml
alert: !include includes/alerts.yaml
automation: !include automations.yaml
automation yaml: !include automation.yaml
camera: !include includes/cameras.yaml
cover: !include includes/covers.yaml
group: !include includes/groups.yaml
input_boolean: !include includes/input_booleans.yaml
input_select: !include includes/input_selects.yaml
input_text: !include includes/input_text.yaml
input_number: !include includes/input_number.yaml
intent_script: !include includes/intent_scripts.yaml
light: !include includes/lights.yaml
mqtt: !include includes/mqtt.yaml
rest_command: !include includes/rest_commands.yaml
rest: !include includes/rest.yaml
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
shell_command: !include includes/shell_commands.yaml
switch: !include includes/switches.yaml
template: !include includes/template.yaml
zone: !include includes/zones.yaml

logger:
  default: warning

history:
websocket_api:
sun:
conversation:
logbook:
person:
config:
mobile_app:
media_source:
wake_on_lan:

homekit:
  advertise_ip: !secret hass_ip
  filter:
    include_entities:
      - cover.single_garage_door
      - cover.double_garage_door
      - input_boolean.jon
      - input_boolean.laura

sonos:
  media_player:
    advertise_addr: !secret hass_ip
    hosts:
      - 192.168.30.38
      - 192.168.30.39
      - 192.168.30.40
      - 192.168.30.41
      - 192.168.30.42
      - 192.168.30.43
      - 192.168.30.44
      - 192.168.30.45
      - 192.168.30.46
      - 192.168.30.47
      - 192.168.30.48
      - 192.168.30.49
      - 192.168.30.51
      - 192.168.30.52
      - 192.168.30.53
