---
default_config:
homeassistant:
  name: !secret name
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  currency: USD
  country: US
  time_zone: !secret ha_tz
  external_url: !secret ext_hass_url
  internal_url: !secret int_hass_url
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - "/tmp"
    - "/config/www"
  media_dirs:
    local: /media
cloud:
energy:
datadog:
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.30.0/24
    - 192.168.31.0/24
  login_attempts_threshold: 3
  ip_ban_enabled: false
tts:
  - platform: google_translate
    service_name: google_say
frontend:
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
    - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
      type: module
    - url: /hacsfiles/custom-sonos-card/custom-sonos-card.js
      type: module
    - url: /hacsfiles/decluttering-card/decluttering-card.js
      type: module
  dashboards:
    wallpanel-dashboard:
      mode: yaml
      title: Wallpanel
      icon: mdi:tablet-dashboard
      show_in_sidebar: false
      filename: wallpanel.yaml
    # ui-lcars:
    #   mode: yaml
    #   title: ncc-main
    #   icon: mdi:tablet-dashboard
    #   show_in_sidebar: true
    #   filename: ui-lcars.yaml
    test-dashboard:
      mode: yaml
      title: test-dashboard
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      filename: test.yaml
system_health:

elkm1:
  host: !secret url_elk
  area:
    exclude: [2-8]
  zone:
    exclude: [33-208]
  output:
    exclude: [1-208]
  counter:
    exclude: [2-64]
  keypad:
    include: [1-3]
  task:
    enabled: false
  thermostat:
    enabled: false
  plc:
    enabled: false
  setting:
    enabled: false

lutron_caseta:
  - host: !secret ra3_ip
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

notify:
  - name: telegram_jon
    platform: telegram
    chat_id: !secret telegram_chat

telegram_bot:
  - platform: polling
    parse_mode: html
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat

calendar:
  - platform: todoist
    token: !secret todoist

####################################################
#                     Includes                     #
####################################################
adaptive_lighting: !include includes/adaptive_lighting.yaml
alert: !include includes/alerts.yaml
automation: !include automations.yaml
automation yaml: !include_dir_merge_list automation
camera: !include includes/cameras.yaml
climate: !include includes/climate.yaml
cover: !include includes/covers.yaml
# fan: !include includes/fans.yaml
group: !include includes/groups.yaml
input_boolean: !include includes/input_booleans.yaml
input_select: !include includes/input_selects.yaml
input_text: !include includes/input_text.yaml
input_number: !include includes/input_number.yaml
intent_script: !include includes/intent_scripts.yaml
ios: !include includes/ios.yaml
light: !include includes/lights.yaml
mqtt: !include includes/mqtt.yaml
rest_command: !include includes/rest_commands.yaml
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
shell_command: !include includes/shell_commands.yaml
switch: !include includes/switches.yaml
template: !include includes/template.yaml
zone: !include includes/zones.yaml

logger:
  default: error

history:
websocket_api:
sun:
conversation:
logbook:
person:
config:
mobile_app:
media_source:
wake_on_lan:

rest:
  - headers:
      Authorization: !secret enphase_api
    verify_ssl: False
    scan_interval: 6
    resource: https://192.168.31.108/ivp/meters/readings
    sensor:
      - name: Power Production
        unique_id: power_production
        value_template: "{{ value_json[0].activePower | int(0) }}"
        device_class: power
        unit_of_measurement: W
        state_class: measurement
        icon: mdi:solar-panel
      - name: Power Consumption
        unique_id: power_consumption
        value_template: "{{ value_json[1].activePower | int(0) }}"
        device_class: power
        unit_of_measurement: W
        state_class: measurement
        icon: mdi:solar-panel
      - name: Energy Production
        unique_id: energy_production
        value_template: "{{ (value_json[0].actEnergyDlvd / 1000 | float(0)) | round(2) }}"
        device_class: energy
        unit_of_measurement: kWh
        state_class: total_increasing
        icon: mdi:solar-panel
      - name: Energy Import
        unique_id: energy_import
        value_template: "{{ (value_json[1].actEnergyDlvd / 1000 | float(0)) | round(2) }}"
        device_class: energy
        unit_of_measurement: kWh
        state_class: total_increasing
        icon: mdi:transmission-tower
      - name: Energy Export
        unique_id: energy_export
        value_template: "{{ (value_json[1].actEnergyRcvd / 1000 | float(0)) | round(2) }}"
        device_class: energy
        unit_of_measurement: kWh
        state_class: total_increasing
        icon: mdi:transmission-tower

weather:
  - platform: template
    name: Local Weather
    condition_template: "{{ states('sensor.hub_hb_00069559_weather') }}"
    temperature_template: "{{ states('sensor.weatherflow_tempest_temperature') | float}}"
    humidity_template: "{{ states('sensor.weatherflow_tempest_humidity')| int }}"
    pressure_template: "{{ states('sensor.weatherflow_tempest_sea_level_pressure')| float }}"
    wind_speed_template: "{{ states('sensor.weatherflow_tempest_wind_speed_avg')| float }}"
    wind_bearing_template: "{{ states('sensor.weatherflow_tempest_wind_bearing_avg')| int }}"
    visibility_template: "{{ states('sensor.weatherflow_tempest_visibility')| float }}"
    forecast_hourly_template: >-
      {% set data = namespace(l = []) %}
      {% for e in state_attr('sensor.hub_hb_00069559_weather', 'hourly_forecast') %}
      {%   set data.l = data.l + [ {
              'datetime': e.datetime,
              'condition': e.condition,
              'temperature': e.temperature,
              'native_apparent_temperature': e.feels_like,
              'pressure': e.pressure,
              'humidity': e.humidity,
              'precipitation': e.precipitation,
              'precipitation_probability': e.precipitation_probability,
              'wind_speed': e.wind_speed,
              'native_wind_gust_speed': e.wind_gust,
              'wind_bearing': e.wind_bearing,
              'uv_index': e.uv
            } ] %}
      {% endfor %}
      {{ data.l }}
    forecast_daily_template: >-
      {% set data = namespace(l = []) %}
      {% for e in state_attr('sensor.hub_hb_00069559_weather', 'daily_forecast') %}
      {%   set data.l = data.l + [ {
              'datetime': e.datetime,
              'condition': e.condition,
              'temperature': e.temperature,
              'templow': e.templow,
              'precipitation': e.precipitation,
              'precipitation_probability': e.precipitation_probability,
              'wind_speed': e.wind_speed,
              'wind_bearing': e.wind_bearing
            } ] %}
      {% endfor %}
      {{ data.l }}

homekit:
  - filter:
      include_entities:
        - binary_sensor.elkm1_kitchen_pir
        - binary_sensor.elkm1_foyer_pir
