# Start of the dwains theme ui-lovelace.yaml
# Don't change anything below this section, only if you know what you are doing

# Do you have any custom resources? Go to the folder dwains-theme/resources/, 
# if you don't have the file custom_resources.yaml then rename the file custom_resources-sample.yaml
# to custom_resources.yaml and place your resources in the file custom_resources.yaml!

# Loading all necessary components for dwains theme...
# Custom Header with some custom configuration (https://github.com/maykar/custom-header)
custom_header:
  !include dwains-theme/plugins/custom_header/configuration.yaml
      
# Button Card Templates folder (https://github.com/custom-cards/button-card#Configuration-Templates)
# These are the templates used to avoid too much duplicate code.      
button_card_templates:
  !include_dir_merge_named dwains-theme/plugins/button-cards-templates        
 
# Start of main lovelace theme 
background: var(--background-image)
views:
  !include_dir_merge_list dwains-theme/views/main/
# End of the dwains theme ui-lovelace.yaml part
######

decluttering_templates:
  cam_history:
    card:
      type: custom:swipe-card
      start_card: 10
      cards:
        - type: picture-entity
          entity: "camera.[[cam]]_history1"
        - type: picture-entity
          entity: "camera.[[cam]]_history2"
        - type: picture-entity
          entity: "camera.[[cam]]_history3"
        - type: picture-entity
          entity: "camera.[[cam]]_history4"
        - type: picture-entity
          entity: "camera.[[cam]]_history5"
        - type: picture-entity
          entity: "camera.[[cam]]_history6"
        - type: picture-entity
          entity: "camera.[[cam]]_history7"
        - type: picture-entity
          entity: "camera.[[cam]]_history8"
        - type: picture-entity
          entity: "camera.[[cam]]_history9"
        - type: picture-entity
          entity: "camera.[[cam]]_history10"
  lock:
    card:
      type: custom:button-card
      entity: lock.[[lock]]
      icon: mdi:lock
      name: "[[name]]"
      show_state: true
      show_last_changed: true
      tap_action:
        action: more-info
      double_tap_action:
        action: toggle
      styles:
        # grid:
        #   - grid-template-columns: 30% 70%
        # img_cell:
        #   - width: 60px
        #   - height: 60px
        name:
          - font-size: 15px
          - color: var(--dwains-theme-names)
        state:
          - font-size: 13px
          - color: var(--dwains-theme-grey)
        label:
          - font-size: 12px
          - color: var(--dwains-theme-grey)
      state:
        - value: "locked"
          icon: mdi:lock-outline
        - value: "unlocked"
          color: red
          icon: mdi:lock-open-variant-outline
