title: test-dashboard
resources:
  - url: /hacsfiles/todoist-card/todoist-card.js
    type: module
  - url: /local/todoist-card.js
    type: module

views:
  - title: panel
    id: home
    icon: mdi:home
    panel: true
    cards:
      - type: custom:layout-card
        layout_type: grid
        layout:
          grid-template-columns: 33% 33% 33%
          grid-template-rows: auto
          grid-template-areas: |
            "one two three"
            "cal cal cal"
        cards:
          - type: picture
            image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
            tap_action:
              action: navigate
              navigation_path: "/test-dashboard/1"
            view_layout:
              grid-area: one
          - type: markdown
            content: |
              DATE
            view_layout:
              grid-area: two
          - type: weather-forecast
            entity: weather.tomorrow_io_home_daily
            show_forecast: false
            view_layout:
              grid-area: three
          - type: calendar
            entities:
              - calendar.local
            view_layout:
              grid-area: cal
  - title: panel
    id: chores
    icon: mdi:home
    panel: true
    cards:
      - type: custom:layout-card
        layout_type: grid
        layout:
          grid-template-columns: 33% 33% 33%
          grid-template-rows: auto
          grid-template-areas: |
            "one two three"
        cards:
          - type: custom:grocy-chores-card
            title: chores
            entity:
              - sensor.grocy_chores
            view_layout:
              grid-area: one
          - type: custom:grocy-chores-card
            title: shopping
            entity:
              - sensor.grocy_shopping_list
            view_layout:
              grid-area: two
          - type: custom:grocy-chores-card
            title: tasks
            entity:
              - sensor.grocy_tasks
            view_layout:
              grid-area: three
