title: ncc-main
views:
  - title: operations
    theme: LCARS Cardassia
    path: sections
    type: sections
    max_columns: 2
    sections:
      - type: grid
        cards:
          - type: markdown
            content: "# u.s.s. reeder"
            card_mod:
              class: header
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.frontyard
            card_mod:
              class: button-small
          - type: horizontal-stack
            cards:
              - type: button
                entity: group.main_floor_lights
                icon: mdi:lightbulb
                name: Main
                show_state: true
                tap_action:
                  action: call-service
                  service: button.press
                  data:
                    entity_id: button.basement_equipment_room_homeowner_kp01_position_3_keypad_main_off
                double_tap_action:
                  action: navigate
                  navigation_path: "/ui-lcars/lights-main"
                card_mod:
                  class: button-bullet
              - type: button
                entity: group.upstairs_lights
                icon: mdi:lightbulb
                name: Upstairs
                show_state: true
                tap_action:
                  action: call-service
                  service: button.press
                  data:
                    entity_id: button.basement_equipment_room_homeowner_kp01_position_3_keypad_second_off
                double_tap_action:
                  action: navigate
                  navigation_path: "/ui-lcars/lights-upstairs"
                card_mod:
                  class: button-capped
          - type: entities
            show_name: false
            show_header_toggle: false
            card_mod:
              class: middle
            entities:
              - entity: binary_sensor.garage_doors
                type: custom:multiple-entity-row
                name: Garage
                show_state: false
                secondary_info: last-changed
                entities:
                  - entity: cover.single_garage_door
                    name: single
                    tap_action:
                      action: toggle
                  - entity: cover.double_garage_door
                    name: double
                    tap_action:
                      action: toggle
          - type: markdown
            card_mod:
              class: footer
            content: "# "
      - type: grid
        cards:
          - type: markdown
            content: "# galaxy class"
            card_mod:
              class: header-right
              style: |
                ha-card.header-right > ha-markdown {
                  border-radius: 0 20px 0 0;
                  height: 100%;
                  display: flex;
                  align-items: flex-end;
                }
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.driveway
            card_mod:
              class: button-small
          - type: horizontal-stack
            cards:
              - type: button
                entity: group.exterior_lights
                icon: mdi:lightbulb
                name: Exterior
                show_state: true
                tap_action:
                  action: call-service
                  service: button.press
                  data:
                    entity_id: button.basement_equipment_room_homeowner_kp01_position_2_keypad_exterior_off
                double_tap_action:
                  action: navigate
                  navigation_path: "/ui-lcars/lights-exterior"
                card_mod:
                  class: button-capped-right
              - type: button
                entity: group.basement_lights
                icon: mdi:lightbulb
                name: Basement
                show_state: true
                tap_action:
                  action: call-service
                  service: button.press
                  data:
                    entity_id: button.basement_equipment_room_homeowner_kp01_position_1_keypad_basement_off
                double_tap_action:
                  action: navigate
                  navigation_path: "/ui-lcars/lights-basement"
                card_mod:
                  class: button-bullet-right
          # - type: markdown
          #   card_mod:
          #     class: footer-open
          #   content: "# "
  # - title: reeder
  #   theme: LCARS Cardassia
  #   id: reeder
  #   icon: mdi:home
  #   cards:
  #     - type: markdown
  #       card_mod:
  #         class: header
  #       content: "# Equipment"
  #     - type: horizontal-stack
  #       cards:
  #         - type: button
  #           name: garage
  #           show_state: true
  #           entity: lock.garage_lock
  #           tap_action:
  #             action: toggle
  #           card_mod:
  #             class: button-bullet
  #         - type: button
  #           name: shop
  #           show_state: true
  #           entity: lock.workshop_lock
  #           tap_action:
  #             action: toggle
  #           card_mod:
  #             class: button-lozenge
  #     - type: button
  #       name: mudroom
  #       show_state: true
  #       entity: lock.mudroom_lock
  #       tap_action:
  #         action: toggle
  #       card_mod:
  #         class: button-bullet
  #     - type: vertical-stack
  #       cards:
  #         - type: markdown
  #           card_mod:
  #             class: header-right
  #           content: "# Cameras"
  #         - type: custom:frigate-card
  #           cameras:
  #             - camera_entity: camera.driveway
  #               live_provider: webrtc-card
  #               title: Driveway
  #           cameras_global:
  #             webrtc_card:
  #               ui: true
  #             controls:
  #               title:
  #                 mode: none
  #           card_mod:
  #             class: middle
#####################################
#   - title: panel
#     theme: LCARS Cardassia
#     id: panel
#     icon: mdi:home
#     panel: true
#     cards:
#       - type: custom:layout-card
#         layout_type: grid
#         layout:
#           grid-template-columns: 33% 33% 33%
#           grid-template-rows: auto
#           mediaquery:
#             "(min-width: 1000px)":
#               grid-template-areas: |
#                 "c1 c2 c3"
#                 "c4 c5 c6"
#             "all":
#               grid-template-areas: |
#                 "c1"
#                 "c2"
#                 "c3"
#                 "c4"
#                 "c5"
#                 "c6"
#         cards:
#           - type: vertical-stack
#             view_layout:
#               grid-area: c1
#             cards:
#               - type: markdown
#                 card_mod:
#                   class: header
#                 content: "# Equipment"
#               - type: entities
#                 show_name: false
#                 show_header_toggle: false
#                 card_mod:
#                   class: middle
#                 entities:
#                   - entity: binary_sensor.garage_doors
#                     type: custom:multiple-entity-row
#                     name: Garage
#                     show_state: false
#                     secondary_info: last-changed
#                     entities:
#                       - entity: cover.single_garage_door
#                         name: single
#                         tap_action:
#                           action: toggle
#                       - entity: cover.double_garage_door
#                         name: double
#                         tap_action:
#                           action: toggle
#               - type: horizontal-stack
#                 cards:
#                   - type: button
#                     name: garage
#                     show_state: true
#                     entity: lock.garage_lock
#                     tap_action:
#                       action: toggle
#                     card_mod:
#                       class: button-bullet
#                   - type: button
#                     name: shop
#                     show_state: true
#                     entity: lock.workshop_lock
#                     tap_action:
#                       action: toggle
#                     card_mod:
#                       class: button-lozenge
#               - type: button
#                 name: mudroom
#                 show_state: true
#                 entity: lock.mudroom_lock
#                 tap_action:
#                   action: toggle
#                 card_mod:
#                   class: button-bullet
#           - type: vertical-stack
#             view_layout:
#               grid-area: c2
#             cards:
#               - type: markdown
#                 card_mod:
#                   class: header-right
#                 content: "# Cameras"
#               - type: custom:frigate-card
#                 cameras:
#                   - camera_entity: camera.driveway
#                     live_provider: webrtc-card
#                     title: Driveway
#                 cameras_global:
#                   webrtc_card:
#                     ui: true
#                   controls:
#                     title:
#                       mode: none
#                 card_mod:
#                   class: middle
#           - type: vertical-stack
#             view_layout:
#               grid-area: c3
#             cards:
#               - type: markdown
#                 card_mod:
#                   class: header
#                 content: "# Climate"
#               - type: weather-forecast
#                 entity: weather.tomorrow_io_home_daily
#                 card_mod:
#                   class: middle
#           - type: vertical-stack
#             view_layout:
#               grid-area: c4
#             cards:
#               - type: entities
#                 show_header_toggle: false
#                 card_mod:
#                   class: middle
#                 entities:
#                   - entity: binary_sensor.anybody_home
#                     type: custom:multiple-entity-row
#                     name: Presence
#                     secondary_info: last-changed
#                     entities:
#                       - entity: binary_sensor.anybody_away
#                   - entity: binary_sensor.anybody_home
#                     type: custom:multiple-entity-row
#                     name: People
#                     hide_state: true
#                     entities:
#                       - entity: person.jon
#                       - entity: person.laura

#               - type: horizontal-stack
#                 cards:
#                   - type: button
#                     entity: group.main_floor_lights
#                     icon: mdi:lightbulb
#                     name: Main
#                     show_state: true
#                     tap_action:
#                       action: call-service
#                       service: button.press
#                       data:
#                         entity_id: button.basement_equipment_room_homeowner_kp01_position_3_keypad_main_off
#                     double_tap_action:
#                       action: navigate
#                       navigation_path: "/ui-lcars/lights-main"
#                     card_mod:
#                       class: button-bullet
#                   - type: button
#                     entity: group.upstairs_lights
#                     icon: mdi:lightbulb
#                     name: Upstairs
#                     show_state: true
#                     tap_action:
#                       action: call-service
#                       service: button.press
#                       data:
#                         entity_id: button.basement_equipment_room_homeowner_kp01_position_3_keypad_second_off
#                     double_tap_action:
#                       action: navigate
#                       navigation_path: "/ui-lcars/lights-upstairs"
#                     card_mod:
#                       class: button-lozenge
#               - type: horizontal-stack
#                 cards:
#                   - type: button
#                     entity: group.basement_lights
#                     icon: mdi:lightbulb
#                     name: Basement
#                     show_state: true
#                     tap_action:
#                       action: call-service
#                       service: button.press
#                       data:
#                         entity_id: button.basement_equipment_room_homeowner_kp01_position_1_keypad_basement_off
#                     double_tap_action:
#                       action: navigate
#                       navigation_path: "/ui-lcars/lights-basement"
#                     card_mod:
#                       class: button-bullet
#                   - type: button
#                     entity: group.exterior_lights
#                     icon: mdi:lightbulb
#                     name: Exterior
#                     show_state: true
#                     tap_action:
#                       action: call-service
#                       service: button.press
#                       data:
#                         entity_id: button.basement_equipment_room_homeowner_kp01_position_2_keypad_exterior_off
#                     double_tap_action:
#                       action: navigate
#                       navigation_path: "/ui-lcars/lights-exterior"
#                     card_mod:
#                       class: button-lozenge
# ##########################################
# # LIGHT SUBVIEWS
# ##########################################
# - title: Lights - Main
#   theme: LCARS Cardassia
#   id: lights-main
#   icon: mdi:lightbulb
#   subview: true
#   path: lights-main
#   panel: true
#   cards:
#     - type: custom:auto-entities
#       card:
#         type: grid
#         columns: 4
#         square: false
#       card_param: cards
#       filter:
#         include:
#           - options:
#               type: tile
#               features:
#                 - type: light-brightness
#             group: group.main_floor_lights
# - title: Lights - Upstairs
#   id: lights-upstairs
#   icon: mdi:lightbulb
#   subview: true
#   path: lights-upstairs
#   panel: true
#   cards:
#     - type: custom:auto-entities
#       card:
#         type: grid
#         columns: 4
#         square: false
#       card_param: cards
#       filter:
#         include:
#           - options:
#               type: tile
#               features:
#                 - type: light-brightness
#             group: group.upstairs_lights
# - title: Lights - Basement
#   id: lights-basement
#   icon: mdi:lightbulb
#   subview: true
#   path: lights-basement
#   panel: true
#   cards:
#     - type: custom:auto-entities
#       card:
#         type: grid
#         columns: 4
#         square: false
#       card_param: cards
#       filter:
#         include:
#           - options:
#               type: tile
#               features:
#                 - type: light-brightness
#             group: group.basement_lights
# - title: Lights - Exterior
#   id: lights-exterior
#   icon: mdi:lightbulb
#   subview: true
#   path: lights-exterior
#   panel: true
#   cards:
#     - type: custom:auto-entities
#       card:
#         type: grid
#         columns: 4
#         square: false
#       card_param: cards
#       filter:
#         include:
#           - options:
#               type: tile
#               features:
#                 - type: light-brightness
#             group: group.exterior_lights
