title: !secret name
resources:
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
    type: module
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: module
  - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
    type: module
  - url: /hacsfiles/custom-sonos-card/custom-sonos-card.js
    type: module

views:
  - title: panel
    id: home
    icon: mdi:home
    panel: true
    view_layout:
      column: 2
    cards:
      - type: custom:layout-card
        layout_type: custom:grid
        layout:
          mediaquery:
            "all":
              grid-template-areas: |
                "one two"
                "three four"
                "five six"
                "seven eight"
        cards:
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.driveway
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: one
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.frontyard
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: two
          - type: horizontal-stack
            view_layout:
              grid-area: three
            cards:
              - type: tile
                entity: group.main_floor_lights
                name: Main
                icon: mdi:lightbulb
                tap_action:
                  action: navigate
                  navigation_path: "/lovelace/lights-main"
                icon_tap_action:
                  action: call-service
                  service: button.press
                  target:
                    entity_id: button.basement_equipment_room_phantom_kp_position_1_keypad_main_off
              - type: tile
                entity: group.upstairs_lights
                name: Upstairs
                icon: mdi:lightbulb
                tap_action:
                  action: navigate
                  navigation_path: "/lovelace/lights-upstairs"
                icon_tap_action:
                  action: call-service
                  service: button.press
                  target:
                    entity_id: button.basement_equipment_room_phantom_kp_position_1_keypad_second_off
          - type: horizontal-stack
            view_layout:
              grid-area: four
            cards:
              - type: tile
                entity: group.basement_lights
                name: Basement
                icon: mdi:lightbulb
                tap_action:
                  action: navigate
                  navigation_path: "/lovelace/lights-basement"
                icon_tap_action:
                  action: call-service
                  service: button.press
                  target:
                    entity_id: button.basement_equipment_room_phantom_kp_position_1_keypad_basement_off
              - type: tile
                entity: group.exterior_lights
                name: Exterior
                icon: mdi:lightbulb
                tap_action:
                  action: navigate
                  navigation_path: "/lovelace/lights-exterior"
                icon_tap_action:
                  action: call-service
                  service: button.press
                  target:
                    entity_id: button.basement_equipment_room_phantom_kp_position_1_keypad_exterior_off
          - type: horizontal-stack
            view_layout:
              grid-area: five
            cards:
              - type: tile
                entity: cover.main_floor_library_shade
                name: Library
                icon: mdi:roller-shade
                features:
                  - type: "cover-open-close"
              - type: tile
                entity: cover.main_floor_kitchen_shades
                name: Kitchen
                icon: mdi:roller-shade
                features:
                  - type: "cover-open-close"
          - type: horizontal-stack
            view_layout:
              grid-area: six
            cards:
              - type: tile
                entity: cover.main_floor_great_room_shades
                name: Great Room
                icon: mdi:roller-shade
                features:
                  - type: "cover-open-close"
              - type: tile
                entity: cover.upstairs_stair_shade
                name: Stairs
                icon: mdi:roller-shade
                features:
                  - type: "cover-open-close"
          - type: "custom:auto-entities"
            show_empty: true
            card:
              title: Important Dates
              type: entities
              show_header_toggle: false
            sort:
              method: state
              numeric: true
            filter:
              include:
                - entity_id: "/(birthday|anniversary|holiday)/"
                  state: < 45
                  options:
                    type: custom:template-entity-row
                    state: |
                      {% if is_state(config.entity, '0') %}
                        today
                      {% elif is_state(config.entity, '1') %}
                        tomorrow
                      {% else %}
                        {{ states(config.entity) }} days
                      {% endif %}
                    # if current_years isnt defined, then add nothing at the front, elif the day is today, then add their current_years, else just add yrs at next
                    secondary: |
                      {% if state_attr(config.entity, 'current_years') == None %}
                      {% elif is_state(config.entity, '0') %}
                        {{ state_attr(config.entity, 'current_years') }} yrs - 
                      {% else %}
                        {{ state_attr(config.entity, 'years_at_anniversary') }} yrs - 
                      {% endif %}
                      {{ as_timestamp(state_attr(config.entity, 'date')) | timestamp_custom('%m/%d/%Y') }}
            view_layout:
              grid-area: seven
          - type: weather-forecast
            entity: weather.tomorrow_io_home_daily
            view_layout:
              grid-area: eight
  - title: Cameras Front
    id: camera-front
    icon: mdi:camera
    panel: true
    cards:
      - type: custom:layout-card
        layout_type: custom:grid
        layout:
          mediaquery:
            "(min-width: 1800px)":
              grid-template-areas: |
                "cam1 cam2 cam3"
                "cam4 . ."
                ". . ."
            "(min-width: 1000px)":
              grid-template-areas: |
                "cam1 cam2"
                "cam3 cam4"
            "all":
              grid-template-areas: |
                "cam1"
                "cam2"
                "cam3"
                "cam4"
        cards:
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.driveway
                live_provider: webrtc-card
                title: Driveway
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: cam1
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.doorbell
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: cam2
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.frontyard
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: cam3
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.garage
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: cam4

  ##########################################
  # CAMERA TAB
  ##########################################
  - title: Cameras Rear
    id: camera-rear
    icon: mdi:camera
    panel: true
    cards:
      - type: custom:layout-card
        layout_type: custom:grid
        layout:
          mediaquery:
            "(min-width: 1800px)":
              grid-template-areas: |
                "cam1 cam2 cam3"
                "cam4 cam5 ."
                ". . ."
            "(min-width: 1000px)":
              grid-template-areas: |
                "cam1 cam2"
                "cam3 cam4"
                "cam5 ."
            "all":
              grid-template-areas: |
                "cam1"
                "cam2"
                "cam3"
                "cam4"
                "cam5"
        cards:
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.deck
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: cam1
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.workshop
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: cam2
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.grilldeck
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: cam3
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.mudroom
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: cam4
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.patio
            cameras_global:
              webrtc_card:
                ui: true
              controls:
                title:
                  mode: none
            view_layout:
              grid-area: cam5
