title: !secret name
resources:
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/decluttering-card/decluttering-card.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/mini-climate-card/mini-climate-card-bundle.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
    type: module
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: module
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
    type: module
  - url: /hacsfiles/custom-sonos-card/custom-sonos-card.js
    type: module

views:
  - title: panel
    id: home
    icon: mdi:home
    panel: true
    layout:
      max_width: 150
      width: 150
    view_layout:
      column: 2
    cards:
      - type: custom:layout-card
        layout_type: custom:grid
        layout:
          mediaquery:
            "all":
              grid-template-areas: |
                "one two"
                "three four"
                "five six"
                "seven ."
        cards:
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.driveway
                webrtc:
                  entity: camera.driveway_rtsp
            view_layout:
              grid-area: one
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.frontyard
                webrtc:
                  entity: camera.frontyard_rtsp
            view_layout:
              grid-area: two
          - type: "custom:auto-entities"
            show_empty: true
            card:
              title: Important Dates
              type: entities
              show_header_toggle: false
            sort:
              method: state
              numeric: true
            filter:
              include:
                - entity_id: "/(birthday|anniversary|holiday)/"
                  state: < 45
                  options:
                    type: custom:template-entity-row
                    state: |
                      {% if is_state(config.entity, '0') %}
                        today
                      {% elif is_state(config.entity, '1') %}
                        tomorrow
                      {% else %}
                        {{ states(config.entity) }} days
                      {% endif %}
                    # if current_years isnt defined, then add nothing at the front, elif the day is today, then add their current_years, else just add yrs at next
                    secondary: |
                      {% if state_attr(config.entity, 'current_years') == None %}
                      {% elif is_state(config.entity, '0') %}
                        {{ state_attr(config.entity, 'current_years') }} yrs - 
                      {% else %}
                        {{ state_attr(config.entity, 'years_at_next_anniversary') }} yrs - 
                      {% endif %}
                      {{ as_timestamp(state_attr(config.entity, 'date')) | timestamp_custom('%m/%d/%Y') }}
            view_layout:
              grid-area: three
          - type: weather-forecast
            entity: weather.tomorrow_io_home_daily
            view_layout:
              grid-area: four
          - type: entities
            show_name: false
            show_header_toggle: false
            entities:
              - entity: alarm_control_panel.elkm1_area_1
                type: custom:multiple-entity-row
                name: Alarm
                show_state: false
                secondary_info: last-changed
                entities:
                  - entity: alarm_control_panel.elkm1_area_1
            view_layout:
              grid-area: five
          # - type: custom:auto-entities
          #   show_empty: false
          #   card:
          #     type: entities
          #     title: Lights On
          #   filter:
          #     include:
          #       - group: group.all_lights
          #         state: "on"
          #   sort:
          #     method: name
          #   view_layout:
          #     grid-area: six

          - type: custom:auto-entities
            card:
              type: custom:layout-card
              layout_type: horizontal
              layout_options:
                width: 100
            filter:
              include:
                - group: group.all_lights
                  state: "on"
                  options:
                    type: custom:button-card
                    entity_id: this.entity_id
                    icon: mdi:lightbulb-on-10
                    show_last_changed: true
                    aspect_ratio: 1/1
                    styles:
                      card:
                        - box-shadow: 0px 0px 10px 1px var(--button-card-light-color)
                      icon:
                        - width: 40%
                        - padding-top: 20px
                      label:
                        - color: gray
                        - font-size: 10px
                        - justify-self: start
                        - padding-left: 10px
                        - padding-top: 0px
                      name:
                        - font-weight: bold
                        - padding-left: 0px
                        - font-size: 12px
                        - white-space: normal
                    tap_action:
                      action: toggle
              exclude:
                - state: unavailable
            sort:
              method: name
            show_empty: false
            view_layout:
              grid-area: six
  - title: Cameras Front
    id: camera-front
    icon: mdi:camera
    panel: true
    cards:
      - type: custom:layout-card
        layout_type: custom:grid
        layout:
          mediaquery:
            "(min-width: 1800px)":
              grid-template-areas: |
                "cam1 cam2 cam3"
                "cam4 . ."
                ". . ."
            "(min-width: 1000px)":
              grid-template-areas: |
                "cam1 cam2"
                "cam3 cam4"
            "all":
              grid-template-areas: |
                "cam1"
                "cam2"
                "cam3"
                "cam4"
        cards:
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.driveway
                webrtc:
                  entity: camera.driveway_rtsp
            view_layout:
              grid-area: cam1
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.a8105_e_0
                webrtc:
                  entity: camera.a8105_e_0
            view_layout:
              grid-area: cam2
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.frontyard
                webrtc:
                  entity: camera.frontyard_rtsp
            view_layout:
              grid-area: cam3
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.garage
                webrtc:
                  entity: camera.garage_rtsp
            view_layout:
              grid-area: cam4

  ##########################################
  # CAMERA TAB
  ##########################################
  - title: Cameras Rear
    id: camera-rear
    icon: mdi:camera
    panel: true
    cards:
      - type: custom:layout-card
        layout_type: custom:grid
        layout:
          mediaquery:
            "(min-width: 1800px)":
              grid-template-areas: |
                "cam1 cam2 cam3"
                "cam4 cam5 ."
                ". . ."
            "(min-width: 1000px)":
              grid-template-areas: |
                "cam1 cam2"
                "cam3 cam4"
                "cam5 ."
            "all":
              grid-template-areas: |
                "cam1"
                "cam2"
                "cam3"
                "cam4"
                "cam5"
        cards:
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.deck
                webrtc:
                  entity: camera.deck_rtsp
            view_layout:
              grid-area: cam1
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.workshop
                webrtc:
                  entity: camera.workshop_rtsp
            view_layout:
              grid-area: cam2
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.grilldeck
                webrtc:
                  entity: camera.grilldeck_rtsp
            view_layout:
              grid-area: cam3
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.mudroom
                webrtc:
                  entity: camera.mudroom_rtsp
            view_layout:
              grid-area: cam4
          - type: custom:frigate-card
            cameras:
              - camera_entity: camera.patio
                webrtc:
                  entity: camera.patio_rtsp
            view_layout:
              grid-area: cam5
