---
cameras:
  - entity: camera.driveway
  - entity: camera.front_door
  - entity: camera.garage
  - entity: camera.daisy
  - entity: camera.deck
  - entity: camera.deckstairs
  - entity: camera.front_door_live
  - entity: camera.kitchen_camera
