---
rooms:
  - name: Main Floor
    light: group.main_floor_lights
    climate: climate.main_thermostat
    humidity: sensor.sunroom_humidity
    motion: group.main_motions
    window: group.main_windows
    door: group.main_doors
    media_player: media_player.living_room_tv
    cover: group.main_floor_covers
    addons:
      - name: Sonos
        icon: fal:speaker
        path: "dwains-theme/addons/rooms/house/sonos/page.yaml"
        button_path: "dwains-theme/addons/rooms/house/sonos/button.yaml"
        data:
          platform: sonos
          speakers:
            - entity: media_player.kitchen
              name: Kitchen
            - entity: media_player.laundry
              name: Laundry
            - entity: media_player.portable
              name: Portable
    more_entities:
      entities:
        - entity: lock.front_door_lock
        - entity: lock.garage_door_lock
    page_entities:
      entities:
        - entity: lock.front_door_lock
        - entity: lock.garage_door_lock
  - name: Upstairs
    icon: mdi:stairs-up
    light: group.upstairs_lights
    climate: climate.upstairs_thermostat
    humidity: sensor.master_entry_humidity
    motion: group.upstairs_motions
    cover: group.upstairs_covers
    addons:
      - name: Sonos
        icon: fal:speaker
        path: "dwains-theme/addons/rooms/house/sonos/page.yaml"
        button_path: "dwains-theme/addons/rooms/house/sonos/button.yaml"
        data:
          platform: sonos
          speakers:
            - entity: media_player.guest_bathroom
              name: Guest Bathroom
            - entity: media_player.master
              name: Master Bathroom
  - name: Basement
    icon: mdi:stairs-down
    light: group.basement_lights
    climate: climate.basement_thermostat
    humidity: sensor.house_humidity
    motion: group.basement_motions
    window: group.basement_windows
    door: group.basement_door
    addons:
      - name: Sonos
        icon: fal:speaker
        path: "dwains-theme/addons/rooms/house/sonos/page.yaml"
        button_path: "dwains-theme/addons/rooms/house/sonos/button.yaml"
        data:
          platform: sonos
          speakers:
            - entity: media_player.gym
              name: Gym
            - entity: media_player.workshop
              name: Workshop
    more_entities:
      entities:
        - entity: switch.water_main_shut_off
  - name: Exterior
    icon: mdi:leaf
    light: group.exterior_lights
    climate: climate.garage_thermostat
    motion: group.exterior_motions
    door: group.garage_doors
    addons:
      - name: Sonos
        icon: fal:speaker
        path: "dwains-theme/addons/rooms/house/sonos/page.yaml"
        button_path: "dwains-theme/addons/rooms/house/sonos/button.yaml"
        data:
          platform: sonos
          speakers:
            - entity: media_player.deck
              name: Deck
            - entity: media_player.garage
              name: Garage
    page_entities:
      entities:
        - entity: fan.patio_fan
  - name: Locks
    icon: mdi:door-closed-lock
    addons:
      - name: Lock History
        path: "dwains-theme/addons/rooms/house/lock_history/page.yaml"
        data:
          entity: lock.front_door_lock
  - name: Camera History
    icon: mdi:camera
    addons:
      - name: History
        icon: mdi:camera
        path: /dwains-theme/addons/rooms/house/camera_history.yaml
  - name: Scene
    icon: mdi:movie-outline
    addons:
      - name: Scene
        icon: mdi:movie-outline
        path: /dwains-theme/addons/rooms/house/scene.yaml
  - name: Miscellaneous
    icon: mdi:atom
    addons:
      - name: Settings
        icon: mdi:wrench
        path: /dwains-theme/addons/rooms/house/settings.yaml
      - name: Anniversaries
        icon: mdi:calendar
        path: /dwains-theme/addons/rooms/house/anniversaries.yaml
