---
#########################################
- alias: "Garage: single is open - close"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/closegarage_single"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Closing the {{ trigger }}"
        show_alert: true
    - service: scene.turn_on
      entity_id: scene.task_002
#########################################
- alias: "Garage: double is open - close"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/closegarage_double"
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: "{{ trigger.event.data.id }}"
        message: "Closing the {{ trigger }}"
        show_alert: true
    - service: scene.turn_on
      entity_id: scene.task_001
#########################################
- alias: "Garage: either door is open for 10min & notify & kill heat if it is on"
  trigger:
    - platform: state
      entity_id:
        - sensor.single_garage
        - sensor.double_garage
      to: "Violated"
      for:
        minutes: 10
  action:
    - choose:
        - conditions: "{{ is_state('climate.garage_thermostat', 'heat') }}"
          sequence:
            - service: notify.telegram_jon
              data_template:
                title: "Temperature Alert!"
                message: "{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}, current temperature is {{ states('sensor.garage_temperature') }}"
            - service: climate.turn_off
              entity_id: climate.garage_thermostat
      default:
        - service: notify.telegram_jon
          data_template:
            title: "Garage open!"
            message: "{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}"
