---
#########################################
- alias: "Automatic Lighting: motion light template"
  id: "Automatic Lighting: motion light template"
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.elkm1_main_bath_pir
        - binary_sensor.elkm1_lounge_pir
        - binary_sensor.elkm1_back_kitchen_pir
        - binary_sensor.elkm1_kitchen_pir
        - binary_sensor.elkm1_gym_pir
      id: pir-on
      to: "on"
    - platform: state
      entity_id:
        - binary_sensor.elkm1_lounge_pir
        - binary_sensor.elkm1_back_kitchen_pir
        - binary_sensor.elkm1_kitchen_pir
        - binary_sensor.elkm1_gym_pir
      id: pir-off
      to: "off"
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.elkm1_main_bath_pir
      id: pir-off
      to: "off"
      for:
        minutes: 3
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: pir-on
            - "{{ is_state('input_boolean.block_interior_motion_lights', 'off') }}"
            - "{{ is_state('binary_sensor.dark_out', 'on') }}"
          sequence:
            - choose:
                - conditions: []
                  sequence:
                    - service: homeassistant.turn_on
                      data_template:
                        entity_id: >
                          {% if trigger.entity_id == 'binary_sensor.elkm1_office_pir' %}
                            light.office_art
                          {% elif trigger.entity_id == 'binary_sensor.elkm1_main_bath_pir' %}
                            light.main_bathroom_toekick
                          {% elif trigger.entity_id == 'binary_sensor.elkm1_lounge_pir' %}
                            switch.bar_cabinets
                          {% elif trigger.entity_id == 'binary_sensor.elkm1_back_kitchen_pir' %}
                            switch.back_kitchen_cabinets
                          {% elif trigger.entity_id == 'binary_sensor.elkm1_kitchen_pir' %}
                            switch.kitchen_cabinets, switch.kitchen_toekick
                          {% elif trigger.entity_id == 'binary_sensor.elkm1_gym_pir' %}
                            light.gym_cans
                          {% endif %}
        - conditions:
            - condition: trigger
              id: pir-off
          sequence:
            - service: homeassistant.turn_off
              data_template:
                entity_id: >
                  {% if trigger.entity_id == 'binary_sensor.elkm1_office_pir' %}
                    light.office_art
                  {% elif trigger.entity_id == 'binary_sensor.elkm1_main_bath_pir' %}
                    light.main_bathroom_toekick
                  {% elif trigger.entity_id == 'binary_sensor.elkm1_lounge_pir' %}
                    switch.bar_cabinets
                  {% elif trigger.entity_id == 'binary_sensor.elkm1_back_kitchen_pir' %}
                    switch.back_kitchen_cabinets
                  {% elif trigger.entity_id == 'binary_sensor.elkm1_kitchen_pir' %}
                    switch.kitchen_cabinets, switch.kitchen_cabinets, switch.kitchen_toekick
                  {% elif trigger.entity_id == 'binary_sensor.elkm1_gym_pir' %}
                    light.gym_cans
                  {% endif %}
