---
- alias: "Location Awareness: leave home & single garage open"
  description: "Leave `home` zone with the single garage open, send a photo notification & prompt to close"
  trigger:
    - platform: state
      entity_id: cover.garage_momentary_single
      to: "open"
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: person.jon
          from: "home"
      timeout: 1800
      continue_on_timeout: false
    - service: notify.telegram_jon
      data_template:
        message: "placeholder"
        data:
          inline_keyboard:
            - "Yes:/closegarage_single, No:/do_nothing"
          photo:
            - url: !secret hik_garage_pic
              caption: "{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}. Close?"
#########################################
- alias: "Location Awareness: leave home & double garage open"
  description: "Leave `home` zone with the double garage open, send a photo notification & prompt to close"
  trigger:
    - platform: state
      entity_id: cover.garage_momentary_double
      to: "open"
  action:
    - wait_for_trigger:
        - platform: state
          entity_id: person.jon
          from: "home"
      timeout: 1800
      continue_on_timeout: false
    - service: notify.telegram_jon
      data_template:
        message: "placeholder"
        data:
          inline_keyboard:
            - "Yes:/closegarage_double, No:/do_nothing"
          photo:
            - url: !secret hik_garage_pic
              caption: "{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}. Close?"
