---
########################################
# monitor device_tracker - https://github.com/andrewjfreyer/monitor
- alias: Jon occupancy on
  trigger:
    - platform: numeric_state
      entity_id: sensor.jon_occupancy_confidence
      above: 10
  action:
    - service: device_tracker.see
      data:
        dev_id: jon_pi
        location_name: home
        source_type: bluetooth
- alias: Jon occupancy off
  trigger:
    - platform: numeric_state
      entity_id: sensor.jon_occupancy_confidence
      below: 10
  action:
    - service: device_tracker.see
      data:
        dev_id: jon_pi
        location_name: not_home
        source_type: bluetooth
- alias: Laura occupancy on
  trigger:
    - platform: numeric_state
      entity_id: sensor.laura_occupancy_confidence
      above: 10
  action:
    - service: device_tracker.see
      data:
        dev_id: laura_pi
        location_name: home
        source_type: bluetooth
- alias: Laura occupancy off
  trigger:
    - platform: numeric_state
      entity_id: sensor.laura_occupancy_confidence
      below: 10
  action:
    - service: device_tracker.see
      data:
        dev_id: laura_pi
        location_name: not_home
        source_type: bluetooth
########################################
# HA restart - restart monitor - ha boot
- alias: "Restart Monitor service on HA startup"
  initial_state: "on"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "monitor/scan/restart"

# ## Publish Message - Arrival Scan
# - alias: Publish Message - Arrival Scan
#   trigger:
#     # - platform: state
#     #   entity_id: binary_sensor.driveway_line_crossing, binary_sensor.house_doors
#     #   from: 'off'
#     #   to: 'on'
#     - platform: state
#       entity_id: binary_sensor.deck_line_crossing, binary_sensor.driveway_line_crossing, binary_sensor.front_door_line_crossing
#       from: 'off'
#       to: 'on'
#   # condition:
#   #   - condition: state
#   #     entity_id: device_tracker.jon_pi
#   #     state: 'not_home'
#   #   - condition: state
#   #     entity_id: device_tracker.laura_pi
#   #     state: 'not_home'
#   action:
#     - service: mqtt.publish
#       data:
#         topic: "monitor/scan/arrive"
# Publish Message - Departure Scan
# https://community.home-assistant.io/t/monitor-reliable-multi-user-distributed-bluetooth-occupancy-presence-detection/68505/1508?u=jon102034050
- alias: Publish Message - Departure Scan
  trigger:
    - platform: state
      entity_id: sensor.front_door, sensor.garage_door, sensor.double_garage, sensor.single_garage
      from: "Violated"
      to: "Normal"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.jon_pi
        state: "home"
      - condition: state
        entity_id: device_tracker.laura_pi
        state: "home"
  action:
    - service: mqtt.publish
      data:
        topic: "monitor/scan/arrive"
    - delay: "00:00:10"
    - service: mqtt.publish
      data:
        topic: "monitor/scan/depart"
    - delay: "00:00:30"
    - service: mqtt.publish
      data:
        topic: "monitor/scan/depart"
    - delay: "00:01:00"
    - service: mqtt.publish
      data:
        topic: "monitor/scan/depart"
    - delay: "00:02:00"
    - service: mqtt.publish
      data:
        topic: "monitor/scan/depart"
