---
########################################
# monitor device_tracker - https://github.com/andrewjfreyer/monitor
## example: https://community.home-assistant.io/t/monitor-reliable-multi-user-distributed-bluetooth-occupancy-presence-detection/68505/1508?u=jon102034050
## example: https://blog.ceard.tech/2021/01/presence-detection-resurrection.html
- alias: "Monitor: Jon occupancy on"
  id: "Monitor: Jon occupancy on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.jon_occupancy_confidence
      above: 10
  action:
    - service: device_tracker.see
      data:
        dev_id: jon_bt
        location_name: home
        source_type: bluetooth
- alias: "Monitor: Jon occupancy off"
  id: "Monitor: Jon occupancy off"
  trigger:
    - platform: numeric_state
      entity_id: sensor.jon_occupancy_confidence
      below: 10
  action:
    - service: device_tracker.see
      data:
        dev_id: jon_bt
        location_name: not_home
        source_type: bluetooth
- alias: "Monitor: Laura occupancy on"
  id: "Monitor: Laura occupancy on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.laura_occupancy_confidence
      above: 10
  action:
    - service: device_tracker.see
      data:
        dev_id: laura_bt
        location_name: home
        source_type: bluetooth
- alias: "Monitor: Laura occupancy off"
  id: "Monitor: Laura occupancy off"
  trigger:
    - platform: numeric_state
      entity_id: sensor.laura_occupancy_confidence
      below: 10
  action:
    - service: device_tracker.see
      data:
        dev_id: laura_bt
        location_name: not_home
        source_type: bluetooth
########################################
- alias: "Monitor: Restart Monitor service on HA startup"
  id: "Monitor: Restart Monitor service on HA startup"
  initial_state: "on"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "monitor/scan/restart"
# ## Publish Message - Arrival Scan
# - alias: Publish Message - Arrival Scan
#   trigger:
#     # - platform: state
#     #   entity_id: binary_sensor.driveway_line_crossing, binary_sensor.house_doors
#     #   from: 'off'
#     #   to: 'on'
#     - platform: state
#       entity_id: binary_sensor.deck_line_crossing, binary_sensor.driveway_line_crossing, binary_sensor.front_door_line_crossing
#       from: 'off'
#       to: 'on'
#   # condition:
#   #   - condition: state
#   #     entity_id: device_tracker.jon_bt
#   #     state: 'not_home'
#   #   - condition: state
#   #     entity_id: device_tracker.laura_bt
#   #     state: 'not_home'
#   action:
#     - service: mqtt.publish
#       data:
#         topic: "monitor/scan/arrive"
# Publish Message - Departure Scan
# - alias: "Monitor: Publish Message - Departure Scan"
#   trigger:
#     - platform: state
#       entity_id: sensor.front_door, sensor.double_garage, sensor.single_garage
#       from: "Violated"
#       to: "Normal"
#   condition:
#     condition: or
#     conditions:
#       - condition: state
#         entity_id: device_tracker.jon_bt
#         state: "home"
#       - condition: state
#         entity_id: device_tracker.laura_bt
#         state: "home"
#   action:
#     - service: script.scan_bt_depart
#########################################
# - alias: "Monitor: arrival scan front door"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.front_door
#       to: "on"
#   action:
#     - wait_for_trigger:
#         - platform: state
#           entity_id: binary_sensor.foyer_pir
#           to: "on"
#       timeout: 10
#       continue_on_timeout: false
#     - service: script.scan_bt_arrive
#########################################
# - alias: "Monitor: arrival scan garage door"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.garage_doors
#       to: "on"
#   action:
#     - wait_for_trigger:
#         - platform: state
#           entity_id: binary_sensor.garage_door
#           to: "on"
#       timeout: 120
#       continue_on_timeout: false
#     - service: script.scan_bt_arrive
#########################################
# - alias: "Monitor: departure scan front door"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.foyer_pir
#       to: "on"
#   action:
#     - wait_for_trigger:
#         - platform: state
#           entity_id: binary_sensor.front_door
#           to: "on"
#       timeout: 240
#       continue_on_timeout: false
#     - service: script.scan_bt_depart
#########################################
# - alias: "Monitor: departure scan garage door"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.garage_door
#       to: "on"
#   action:
#     - wait_for_trigger:
#         - platform: state
#           entity_id: binary_sensor.garage_doors
#           to: "on"
#       timeout: 240
#       continue_on_timeout: false
#     - service: script.scan_bt_depart
#########################################
- alias: "Monitor: departure scan"
  id: "Monitor: departure scan"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.garage_doors
        - binary_sensor.front_door
      to: "on"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.jon_bt
        state: "home"
      - condition: state
        entity_id: device_tracker.laura_bt
        state: "home"
  action:
    - service: script.scan_bt_depart
