---
####################################################
# Different scenarios for cloud disconnect/reconnect
#   - arm alarm night, all ppl home: kill cloud
#   - wake up | either person leaves | vacation started: enable cloud
####################################################
- alias: "Sleeping start, all home: nabucasa disconnect"
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.anybody_away
      state: "off"
  action:
    - service: cloud.remote_disconnect

- alias: "Anybody leaves OR vacation on OR sleep off: nabucasa connect"
  trigger:
    - platform: state
      entity_id: binary_sensor.anybody_away
      to: "on"
    - platform: state
      entity_id: binary_sensor.vacation_status
      to: "on"
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "off"
  action:
    - service: cloud.remote_connect
