---
########################################################################################################################
# Different scenarios for cloud disconnect/reconnect
#   - arm alarm night, all phones are here: kill cloud
#   - alarm disarmed, all phones here, kill cloud
#   - both phones show home, kill cloud
#   - either phone leaves: enable cloud
#   - vacation started, enable cloud
########################################
# nabu casa cloud disconnect/reconnect
- alias: "Sleeping, phones home: remote UI disconnect"
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "on"
  condition:
    - condition: state
      entity_id: person.jon
      state: "home"
    - condition: state
      entity_id: person.laura
      state: "home"
  action:
    - service: cloud.remote_disconnect
    # - service: notify.telegram_jon
    #   data_template:
    #     message: "Cloud Disconnect at night: {{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}."

- alias: "Not sleeping, phones home: remote UI disconnect"
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "off"
  condition:
    - condition: state
      entity_id: person.jon
      state: "home"
    - condition: state
      entity_id: person.laura
      state: "home"
  action:
    - service: cloud.remote_disconnect
    # - service: notify.telegram_jon
    #   data_template:
    #     message: "Cloud Disconnect at morning: {{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}."

- alias: "jons phone home (and lauras is home): remote UI disconnect"
  trigger:
    - platform: state
      entity_id: person.jon
      to: "home"
  condition:
    - condition: state
      entity_id: person.laura
      state: "home"
  action:
    - service: cloud.remote_disconnect
    # - service: notify.telegram_jon
    #   data_template:
    #     message: "Cloud Disconnect when phone is home: {{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}."
- alias: "lauras phone home (and jons is home): remote UI disconnect"
  trigger:
    - platform: state
      entity_id: person.laura
      to: "home"
  condition:
    - condition: state
      entity_id: person.jon
      state: "home"
  action:
    - service: cloud.remote_disconnect
    # - service: notify.telegram_jon
    #   data_template:
    #     message: "Cloud Disconnect when phone is home: {{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}."

- alias: "Phone left: remote UI connect"
  trigger:
    - platform: state
      entity_id: person.jon
      to: "not_home"
    - platform: state
      entity_id: person.laura
      from: "home"
      to: "not_home"
  action:
    - service: cloud.remote_connect
    # - service: notify.telegram_jon
    #   data_template:
    #     message: "Cloud Connect when device left: {{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}."

- alias: "Vacation on, enable remote UI connect"
  trigger:
    - platform: state
      entity_id: binary_sensor.vacation_status
      to: "on"
  action:
    - service: cloud.remote_connect
    # - service: notify.telegram_jon
    #   data_template:
    #     message: "Cloud Connect on vacation mode: {{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}."
