---
####################################################
# Different scenarios for cloud disconnect/reconnect
#   - arm alarm night, all ppl are here: kill cloud
#   - wake up, all ppl here, kill cloud
#   - both ppl show home, kill cloud
#   - either person leaves: enable cloud
#   - vacation started, enable cloud
####################################################
- alias: "Sleeping start or sleeping end, both home: nabucasa disconnect"
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "on"
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "off"
  condition:
    - condition: state
      entity_id: binary_sensor.anybody_away
      state: "off"
  action:
    - service: cloud.remote_disconnect

- alias: "Everybody home: nabucasa disconnect"
  trigger:
    - platform: state
      entity_id: binary_sensor.anybody_away
      to: "off"
  action:
    - service: cloud.remote_disconnect

- alias: "Anybody leaves or vacation on: nabucasa connect"
  trigger:
    - platform: state
      entity_id: binary_sensor.anybody_away
      to: "on"
    - platform: state
      entity_id: binary_sensor.vacation_status
      to: "on"
  action:
    - service: cloud.remote_connect
