---
- alias: "Nest: testing"
  id: "Nest: testing"
  description: "Testing nest events"
  trigger:
    - platform: event
      event_type: nest_event
      event_data:
        type: "camera_person"
  action:
    - service: system_log.write
      data_template:
        message: "Found a person! {{trigger.event.data.type}}"
        level: error
    - service: homeassistant.toggle
      entity_id: light.loft_lamp
