#########################################
- alias: "SELLING: wake mode"
  id: "SELLING: wake mode"
  trigger:
    - platform: time
      at: "07:00:00"
  action:
    - service: climate.set_temperature
      data:
        temperature: 70
      target:
        entity_id:
          - climate.basement_thermostat
#########################################
- alias: "SELLING: night mode"
  id: "SELLING: night mode"
  trigger:
    - platform: time
      at: "19:00:00"
  action:
    - service: climate.set_temperature
      data:
        temperature: 62
      target:
        entity_id:
          - climate.basement_thermostat
#########################################
