---
# set the temperature ONLY if we're not on vacation AND one or more of us are home
- alias: Thermostats - morning - cooling
  trigger:
    - platform: time
      at: "04:30:00"
  condition:
    - condition: state
      entity_id: climate.main_thermostat
      state: cool
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jon
          state: "home"
        - condition: state
          entity_id: person.laura
          state: "home"
  action:
    - service: scene.turn_on
      entity_id: scene.cool_77_auto
# set the temperature ONLY if we're not on vacation AND one or more of us are home
- alias: Thermostats - morning - heating
  trigger:
    platform: time
    at: "04:30:00"
  condition:
    - condition: state
      entity_id: climate.main_thermostat
      state: heat
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jon
          state: "home"
        - condition: state
          entity_id: person.laura
          state: "home"
  action:
    - service: scene.turn_on
      entity_id: scene.heat_70_auto
#########################################
# set the temperature back for work ONLY if we're not on vacation AND both people are not_home
- alias: Thermostats - work - cooling
  trigger:
    platform: time
    at: "08:00:00"
  condition:
    - condition: state
      entity_id: climate.main_thermostat
      state: cool
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
    - condition: and
      conditions:
        - condition: state
          entity_id: person.jon
          state: "not_home"
        - condition: state
          entity_id: person.laura
          state: "not_home"
  action:
    - service: scene.turn_on
      entity_id: scene.cool_78_auto
- alias: Thermostats - work - heating
  trigger:
    platform: time
    at: "08:00:00"
  condition:
    - condition: state
      entity_id: climate.main_thermostat
      state: heat
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
    - condition: and
      conditions:
        - condition: state
          entity_id: person.jon
          state: "not_home"
        - condition: state
          entity_id: person.laura
          state: "not_home"
  action:
    - service: scene.turn_on
      entity_id: scene.heat_67_auto
#########################################
# (probably) getting home from work (or soon), make sure were not on vacation, and set the temps to normal
- alias: Thermostats - home from work - cooling
  trigger:
    platform: time
    at: "16:00:00"
  condition:
    - condition: state
      entity_id: climate.main_thermostat
      state: cool
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.cool_77_auto
- alias: Thermostats - home from work - heating
  trigger:
    platform: time
    at: "16:00:00"
  condition:
    - condition: state
      entity_id: climate.main_thermostat
      state: heat
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.heat_71_auto
#########################################
# when we start sleeping, and we're not on vacation, set the temps back
- alias: Thermostats - bed - cooling
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "on"
  condition:
    - condition: state
      entity_id: climate.main_thermostat
      state: cool
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.cool_78_auto
- alias: Thermostats - bed - heating
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "on"
  condition:
    - condition: state
      entity_id: climate.main_thermostat
      state: heat
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.heat_66_auto
