---
- alias: "HVAC: set temps in the morning (if were not on vacation and somebody is home"
  trigger:
    - platform: time
      at: "04:30:00"
  condition:
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: person.jon
          state: "home"
        - condition: state
          entity_id: person.laura
          state: "home"
  action:
    - choose:
        - conditions: "{{ is_state('climate.main_thermostat'), 'cool' }}"
          sequence:
            - service: scene.turn_on
              entity_id: scene.cool_76_auto
      default:
        - service: scene.turn_on
          entity_id: scene.heat_72_auto
#########################################
- alias: "HVAC: set back temps at 8am only if were not on vacation and nobody is home"
  trigger:
    platform: time
    at: "08:00:00"
  condition:
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
    - condition: and
      conditions:
        - condition: state
          entity_id: person.jon
          state: "not_home"
        - condition: state
          entity_id: person.laura
          state: "not_home"
  action:
    - choose:
        - conditions: "{{ is_state('climate.main_thermostat'), 'cool' }}"
          sequence:
            - service: scene.turn_on
              entity_id: scene.cool_78_auto
      default:
        - service: scene.turn_on
          entity_id: scene.heat_67_auto
#########################################
- alias: "HVAC: home from work (4pm) & set temps to normal (only when were not on vacation)"
  trigger:
    platform: time
    at: "16:00:00"
  condition:
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
  action:
    - choose:
        - conditions: "{{ is_state('climate.main_thermostat'), 'cool' }}"
          sequence:
            - service: scene.turn_on
              entity_id: scene.cool_76_auto
      default:
        - service: scene.turn_on
          entity_id: scene.heat_72_auto
#########################################
- alias: "HVAC: start sleeping set the thermostats back"
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.vacation_status
      state: "off"
  action:
    - choose:
        - conditions: "{{ is_state('climate.main_thermostat'), 'cool' }}"
          sequence:
            - service: scene.turn_on
              entity_id: scene.cool_78_auto
      default:
        - service: scene.turn_on
          entity_id: scene.heat_70_auto
