---
#########################################
- alias: "Unifi: Port forward enable wireguard port forward if anybody leaves"
  id: "Unifi: Port forward enable wireguard port forward if anybody leaves"
  trigger:
    - platform: state
      entity_id: binary_sensor.anybody_away
      to: "on"
  action:
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: !secret wireguard_name
        enabled: "true"
        dst_port: !secret wireguard_port
        ip: !secret hass_ip
        fwd_port: !secret wireguard_port
        proto: !secret wireguard_proto
        id: !secret wireguard_id
        unifi_site: !secret unifi_site
        src: "any"
- alias: "Unifi: Port forward disable wireguard port forward when we get home"
  id: "Unifi: Port forward disable wireguard port forward when we get home"
  trigger:
    - platform: state
      entity_id: binary_sensor.anybody_away
      to: "off"
  action:
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: !secret wireguard_name
        enabled: "false"
        dst_port: !secret wireguard_port
        ip: !secret hass_ip
        fwd_port: !secret wireguard_port
        proto: !secret wireguard_proto
        id: !secret wireguard_id
        unifi_site: !secret unifi_site
        src: "any"
#########################################
- alias: "Unifi: Port forward enable NAS port forward for nightly backup at 1:58am"
  id: "Unifi: Port forward enable NAS port forward for nightly backup at 1:58am"
  trigger:
    platform: time
    at: "1:58:00"
  action:
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: !secret nas_name
        enabled: "true"
        dst_port: !secret nas_port_ext
        ip: !secret nas_ip
        fwd_port: !secret nas_port_int
        proto: !secret nas_proto
        id: !secret nas_id
        unifi_site: !secret unifi_site
        src: any
- alias: "Unifi: Port forward disable NAS port forward for backup"
  id: "Unifi: Port forward disable NAS port forward for backup"
  trigger:
    platform: time
    at: "2:58:00"
  action:
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: !secret nas_name
        enabled: "false"
        dst_port: !secret nas_port_ext
        ip: !secret nas_ip
        fwd_port: !secret nas_port_int
        proto: !secret nas_proto
        id: !secret nas_id
        unifi_site: !secret unifi_site
        src: any
#########################################
- alias: "Unifi: garage camera force reboot weekly"
  id: "Unifi: garage camera force reboot weekly"
  description: "garage cam kinda sucks and needs to be rebooted pretty often"
  trigger:
    platform: time
    at: "3:57:00"
  condition:
    - condition: time
      weekday:
        - sun
  action:
    - service: shell_command.unifi_powercycle
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        mac: !secret unifi_poe48_macaddr
        port: 14
        cmd: "power-cycle"
#########################################
- alias: "Unifi: theatre ap reboot"
  id: "Unifi: theatre ap reboot"
  description: "testing an access point reboot"
  trigger:
    platform: time
    at: "3:55:00"
  condition:
    - condition: time
      weekday:
        - sun
  action:
    - service: shell_command.unifi_powercycle_device
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        mac: !secret unifi_aptheatre_macaddr
        reboot_type: "soft"
        cmd: "restart"
####################################################
# Different scenarios for cloud disconnect/reconnect
#   - arm alarm night, all ppl home: kill cloud
#   - wake up | either person leaves | vacation started: enable cloud
####################################################
- alias: "Cloudflare: sleep starting & all home & portfwd disconnect"
  id: "Cloudflare: sleep starting & all home & portfwd disconnect"
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.anybody_away
      state: "off"
  action:
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758d6e38099208487a9d4a"
        unifi_site: !secret unifi_site
        src: "173.245.48.0/20"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758d9538099208487a9ecb"
        unifi_site: !secret unifi_site
        src: "103.21.244.0/22"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758daa38099208487a9fd0"
        unifi_site: !secret unifi_site
        src: "103.22.200.0/22"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758dbf38099208487a9fd1"
        unifi_site: !secret unifi_site
        src: "103.31.4.0/22"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758dde38099208487a9fff"
        unifi_site: !secret unifi_site
        src: "141.101.64.0/18"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758e0a38099208487aa0f2"
        unifi_site: !secret unifi_site
        src: "108.162.192.0/18"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758e2638099208487aa135"
        unifi_site: !secret unifi_site
        src: "190.93.240.0/20"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758e5338099208487aa31f"
        unifi_site: !secret unifi_site
        src: "188.114.96.0/20"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758ea238099208487aa4e4"
        unifi_site: !secret unifi_site
        src: "197.234.240.0/22"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758ebb38099208487aa613"
        unifi_site: !secret unifi_site
        src: "198.41.128.0/17"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758ed038099208487aa614"
        unifi_site: !secret unifi_site
        src: "162.158.0.0/15"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758ee138099208487aa6c3"
        unifi_site: !secret unifi_site
        src: "104.16.0.0/13"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758ef938099208487aa6c9"
        unifi_site: !secret unifi_site
        src: "104.24.0.0/14"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758f0b38099208487aa718"
        unifi_site: !secret unifi_site
        src: "172.64.0.0/13"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "false"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758f1d38099208487aa7cf"
        unifi_site: !secret unifi_site
        src: "131.0.72.0/22"

- alias: "Cloudflare: anybody leaves OR vacation on OR sleep off & portfwd connect"
  id: "Cloudflare: anybody leaves OR vacation on OR sleep off & portfwd connect"
  trigger:
    - platform: state
      entity_id: binary_sensor.anybody_away
      to: "on"
    - platform: state
      entity_id: binary_sensor.vacation_status
      to: "on"
    - platform: state
      entity_id: binary_sensor.sleep_status
      to: "off"
  action:
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758d6e38099208487a9d4a"
        unifi_site: !secret unifi_site
        src: "173.245.48.0/20"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758d9538099208487a9ecb"
        unifi_site: !secret unifi_site
        src: "103.21.244.0/22"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758daa38099208487a9fd0"
        unifi_site: !secret unifi_site
        src: "103.22.200.0/22"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758dbf38099208487a9fd1"
        unifi_site: !secret unifi_site
        src: "103.31.4.0/22"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758dde38099208487a9fff"
        unifi_site: !secret unifi_site
        src: "141.101.64.0/18"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758e0a38099208487aa0f2"
        unifi_site: !secret unifi_site
        src: "108.162.192.0/18"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758e2638099208487aa135"
        unifi_site: !secret unifi_site
        src: "190.93.240.0/20"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758e5338099208487aa31f"
        unifi_site: !secret unifi_site
        src: "188.114.96.0/20"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758ea238099208487aa4e4"
        unifi_site: !secret unifi_site
        src: "197.234.240.0/22"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758ebb38099208487aa613"
        unifi_site: !secret unifi_site
        src: "198.41.128.0/17"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758ed038099208487aa614"
        unifi_site: !secret unifi_site
        src: "162.158.0.0/15"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758ee138099208487aa6c3"
        unifi_site: !secret unifi_site
        src: "104.16.0.0/13"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758ef938099208487aa6c9"
        unifi_site: !secret unifi_site
        src: "104.24.0.0/14"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758f0b38099208487aa718"
        unifi_site: !secret unifi_site
        src: "172.64.0.0/13"
    - service: shell_command.unifi_portfwd
      data:
        username: !secret unifi_usr
        password: !secret unifi_pwd
        baseurl: !secret unifi_ip
        name: "cf"
        enabled: "true"
        dst_port: !secret hass_port_ext
        ip: !secret hass_ip
        fwd_port: !secret hass_port_int
        proto: !secret hass_proto
        id: "61758f1d38099208487aa7cf"
        unifi_site: !secret unifi_site
        src: "131.0.72.0/22"
