---
#########################################
- alias: "Vacation Mode: turn off all lights at 23:30"
  id: "Vacation Mode: turn off all lights at 23:30"
  trigger:
    - platform: time
      at: "23:30:00"
  condition:
    - condition: state
      entity_id: binary_sensor.vacation
      state: "on"
  action:
    - service: button.press
      entity_id: button.basement_equipment_room_phantom_kp_position_1_keypad_all_off
#########################################
- alias: "Vacation Mode: notify if a garage door opens"
  id: "Vacation Mode: notify if a garage door opens"
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_doors
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.vacation
      state: "on"
  action:
    - service: telegram_bot.send_photo
      data_template:
        url: "http://192.168.30.249:5005/api/garage/latest.jpg"
        caption: "One of the {{ trigger.to_state.attributes.friendly_name }} is open 💀"
#########################################
- alias: "Vacation Mode: enabled"
  id: "Vacation Mode: enabled"
  trigger:
    - platform: state
      entity_id: binary_sensor.vacation
      to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: switch.basement_equipment_room_recirculation_pump
    - service: cover.close_cover
      entity_id: group.all_shades
    - choose: # check the locks, notify & lock if unlocked
        - conditions: "{{ states('sensor.doors_unlocked_number') | int > 0 }}"
          sequence:
            - service: notify.telegram_jon
              data_template:
                title: "{{ states('sensor.doors_unlocked_number') }} door(s) UNLOCKED!"
                message: "Locking {{ states('sensor.doors_unlocked') }}"
            - service: script.lock_doors
    - service: notify.telegram_jon
      data:
        title: "Ran vacation mode on!"
        message: |
          Reminder: 
          * set back temps on thermostats
          * set vacation mode on water heater
          * depending how long you're gone, maybe turn off the water main?

          This automation already performed the following:
          * turned off recirc pump
          * locked house locks
          * closed all blinds
          * turned off lights & TVs

#########################################
# - alias: "Vacation Mode: return"
#   id: "Vacation Mode: return"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.vacation
#       to: "off"
#   condition:
#     - condition: template
#       value_template: "{{ not is_state('climate.main_thermostat', 'heat') }}"
#   action:
#     - service: homeassistant.turn_on
#       entity_id: switch.water_main_shut_off
#     - service: climate.set_temperature
#       data:
#         entity_id:
#           - climate.upstairs_thermostat
#           - climate.main_thermostat
#           - climate.basement_thermostat
#         temperature: 77
#         hvac_mode: cool
#     - service: notify.telegram_jon
#       data:
#         title: "Ran vacation mode (summer): off!"
#         message: "turned on water main, set temps to normal, turned on recirc pump, removed vacation mode on water heater"
