---
#########################################
# on vacation, winter, close the main water valve, set temperatures back, set water heater to vacation, & turn off recirculation pump
- alias: "on vacation, winter, close the main water valve, set temperatures back, set water heater to vacation, & turn off recirculation pump"
  trigger:
    - platform: state
      entity_id: binary_sensor.vacation_status
      to: "on"
  condition:
    - condition: state
      entity_id: climate.main_thermostat
      state: "heat"
  action:
    - service: homeassistant.turn_off
      entity_id: switch.water_main_shut_off
    - service: climate.set_temperature
      data:
        entity_id:
          - climate.upstairs_thermostat
          - climate.main_thermostat
          - climate.basement_thermostat
        temperature: 62
        hvac_mode: heat
    - service: climate.set_temperature
      data:
        entity_id:
          - climate.garage_thermostat
        temperature: 42
        hvac_mode: heat
    # - service: water_heater.econet_add_vacation
    #   data:
    #     entity_id: water_heater.heat_pump_water_heater_gen_4
    #     end_date: "{{ (now().strftime('%s') | float + (10080*60)) }}"
    - service: homeassistant.turn_off
      entity_id: switch.equipment_room_recirculation_pump
    - service: notify.telegram_jon
      data:
        title: "Ran vacation (winter) mode: on!"
        message: "set back temps, turned off recirc pump, set vacation mode on water heater,turned off water main"
#########################################
# return from vacation (winter), open the main water valve, remove the rheem water heater vacation hold, set temps back
- alias: "return from vacation (winter)"
  trigger:
    - platform: state
      entity_id: binary_sensor.vacation_status
      to: "off"
  condition:
    - condition: state
      entity_id: climate.main_thermostat
      state: "heat"
  action:
    - service: homeassistant.turn_on
      entity_id: switch.water_main_shut_off
    # - service: water_heater.econet_delete_vacation
    #   entity_id: water_heater.heat_pump_water_heater_gen_4
    - service: climate.set_temperature
      data:
        entity_id:
          - climate.upstairs_thermostat
          - climate.main_thermostat
          - climate.basement_thermostat
        temperature: 70
        hvac_mode: heat
    - service: notify.telegram_jon
      data:
        title: "Ran vacation mode (winter): off!"
        message: "turned on water main, set temps to normal, turned on recirc pump, removed vacation mode on water heater"
