---
#########################################
- alias: "Christmas: roof lights on (only in december)"
  trigger:
    - platform: time
      at: "17:00:00"
  condition:
    - condition: template
      value_template: '{{ now().strftime("%m")|int == 12 }}'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.exterior_light
#########################################
- alias: "Christmas: trees on (only in december) if occupied"
  trigger:
    - platform: time
      at: "17:00:00"
  condition:
    - condition: template
      value_template: '{{ now().strftime("%m")|int == 12 }}'
    - condition: state
      entity_id: person.laura
      state: "home"
  action:
    - service: homeassistant.turn_on
      entity_id: group.christmasTrees
#########################################
- alias: "Christmas: turn off at 11pm (only in december)"
  trigger:
    platform: time
    at: "23:00:00"
  condition:
    - condition: template
      value_template: '{{ now().strftime("%m")|int == 12 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: group.christmasLights
#########################################
- alias: "Christmas: turn off when sleeping starts (only in december)"
  trigger:
    - platform: state
      entity_id: binary_sensor.sleep_status
      from: "off"
      to: "on"
  condition:
    - condition: template
      value_template: '{{ now().strftime("%m")|int == 12 }}'
  action:
    - service: homeassistant.turn_off
      entity_id: group.christmasLights
#########################################
- alias: "Christmans: lights off/on with geolocation presence (only in Dec)"
  trigger:
    - platform: state
      entity_id: person.laura
      to: "home"
    - platform: state
      entity_id: person.laura
      to: "not_home"
  condition:
    - condition: template
      value_template: '{{ now().strftime("%m")|int == 12 }}'
    - condition: time
      after: "17:00:00"
    - condition: time
      before: "23:00:00"
  action:
    - service_template: >
        {% if trigger.to_state.state == 'home' %}homeassistant.turn_on
        {% else %}homeassistant.turn_off{% endif %}
      entity_id: group.christmasTrees
    - service: notify.telegram_jon
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}. Christmas trees are toggled"
#########################################
- alias: "Christmas: turn off when laura gets in bed (only in december)"
  trigger:
    - platform: state
      entity_id: binary_sensor.sleepnumber_firmness_control_sleepiq_dual_boxed_laura_is_in_bed
      from: "off"
      to: "on"
  condition:
    - condition: template
      value_template: '{{ now().strftime("%m")|int == 12 }}'
    - condition: time
      after: "17:00:00"
    - condition: time
      before: "23:59:59"
  action:
    - service: homeassistant.turn_off
      entity_id: group.christmasTrees
