---
- platform: workday
  country: US

- platform: bayesian
  name: dark out?
  prior: 0.5
  probability_threshold: 0.84
  observations:
    - entity_id: sensor.cloud_cover
      prob_given_true: 0.75
      platform: numeric_state
      above: 90
    # - entity_id: sensor.main_tv_lux
    #   prob_given_true: 0.90
    #   platform: numeric_state
    #   below: 110
    # - entity_id: sensor.whole_house_luminance_sensor_main
    #   prob_given_true: 0.95
    #   platform: numeric_state
    #   below: 100
    # - entity_id: 'sensor.bathroom_luminance_sensor_main'
    #   prob_given_true: 0.95
    #   platform: numeric_state
    #   below: 100
    - entity_id: sensor.sun_elevation
      prob_given_true: 0.6
      platform: numeric_state
      below: 20
    - entity_id: sensor.sun_elevation
      prob_given_true: 0.75
      platform: numeric_state
      below: 10
    - entity_id: sensor.sun_elevation
      prob_given_true: 0.85
      platform: numeric_state
      below: 5
    - entity_id: sun.sun
      prob_given_true: 1
      platform: state
      to_state: "below_horizon"
# - platform: bayesian
#   name: office occupancy
#   prior: 0.5
#   probability_threshold: 0.70
#   observations:
#     - platform: "numeric_state"
#       entity_id: "sensor.sonoff2_energy_apparentpower"
#       prob_given_true: 0.99
#       prob_given_false: 0.3
#       above: 24
#     - platform: "state"
#       entity_id: "binary_sensor.office_multi_motion"
#       prob_given_true: 0.95
#       prob_given_false: 0.3
#       to_state: "on"

# # rtl_433 sensors
# - platform: mqtt
#   name: Nursery Acurite Battery
#   state_topic: "rtl_433/Acurite-Tower/4303"
#   payload_on: "0"
#   payload_off: "1"
#   device_class: battery
#   value_template: "{{ value_json.battery_ok }}"
# - platform: mqtt
#   name: Gym Acurite Battery
#   state_topic: "rtl_433/Acurite-Tower/14641"
#   payload_on: "0"
#   payload_off: "1"
#   device_class: battery
#   value_template: "{{ value_json.battery_ok }}"
# - platform: mqtt
#   name: Kitchen Freezer Battery
#   state_topic: "rtl_433/Acurite-986/15488"
#   payload_on: "0"
#   payload_off: "1"
#   device_class: battery
#   value_template: "{{ value_json.battery_ok }}"
# - platform: mqtt
#   name: Kitchen Fridge Battery
#   state_topic: "rtl_433/Acurite-986/37649"
#   payload_on: "0"
#   payload_off: "1"
#   device_class: battery
#   value_template: "{{ value_json.battery_ok }}"
# - platform: mqtt
#   name: Bar Freezer Battery
#   state_topic: "rtl_433/Acurite-986/50597"
#   payload_on: "0"
#   payload_off: "1"
#   device_class: battery
#   value_template: "{{ value_json.battery_ok }}"
# - platform: mqtt
#   name: Bar Fridge Battery
#   state_topic: "rtl_433/Acurite-986/17933"
#   payload_on: "0"
#   payload_off: "1"
#   device_class: battery
#   value_template: "{{ value_json.battery_ok }}"
# - platform: mqtt
#   state_topic: "rtl_433/Kerui-Security/843225"
#   device_class: motion
#   name: Kerui PIR
#   value_template: "{{ value_json.state }}"
#   payload_on: "motion"
#   off_delay: 10

# - platform: template
#   sensors:
#     hvac:
#       friendly_name: "hvac status"
#       value_template: >-
#         {{ states.climate.basement_thermostat.attributes['hvac_action'] != "idle"
#         or states.climate.main_thermostat.attributes['hvac_action'] != "idle"
#         or states.climate.upstairs_thermostat.attributes['hvac_action'] != "idle" }}
#     hvac_heat:
#       friendly_name: "hvac heat status"
#       value_template: >-
#         {{ states.climate.basement_thermostat.attributes['hvac_action'] == "heating"
#         or states.climate.main_thermostat.attributes['hvac_action'] == "heating"
#         or states.climate.upstairs_thermostat.attributes['hvac_action'] == "heating" }}
#     hvac_ac:
#       friendly_name: "hvac ac status"
#       value_template: >-
#         {{ states.climate.basement_thermostat.attributes['hvac_action'] == "cooling"
#         or states.climate.main_thermostat.attributes['hvac_action'] == "cooling"
#         or states.climate.upstairs_thermostat.attributes['hvac_action'] == "cooling" }}
#     evelyns_room_occupied:
#       device_class: occupancy
#       friendly_name: "Evelyns Room Occupied"
#       value_template: >-
#         {{ states.binary_sensor.evelyns_room_occupancy.state == "on"
#         or states.binary_sensor.evelyn_multi_motion.state == "on" }}
#     loft_occupied:
#       device_class: occupancy
#       friendly_name: "Loft Occupied"
#       value_template: >-
#         {{ states.binary_sensor.loft_person_motion.state == "on"
#         or states.binary_sensor.loft_multi_motion.state == "on" }}
