---
- platform: ffmpeg
  input: !secret workshop-rtsp
  name: workshop-rtsp
- platform: ffmpeg
  input: !secret deck-rtsp
  name: deck-rtsp
- platform: ffmpeg
  input: !secret frontyard-rtsp
  name: frontyard-rtsp
- platform: ffmpeg
  input: !secret garage-rtsp
  name: garage-rtsp
- platform: ffmpeg
  input: !secret grilldeck-rtsp
  name: grilldeck-rtsp
- platform: ffmpeg
  input: !secret mudroom-rtsp
  name: mudroom-rtsp
- platform: ffmpeg
  input: !secret driveway-rtsp
  name: driveway-rtsp
- platform: ffmpeg
  input: !secret patio-rtsp
  name: patio-rtsp
