---
###################################
# mjpeg cameras
- platform: mjpeg
  mjpeg_url: http://192.168.45.116:80/Streaming/Channels/2/preview
  name: Front Door
  username: admin
  password: !secret hik_pwd
- platform: mjpeg
  mjpeg_url: http://192.168.45.111:80/Streaming/Channels/2/preview
  name: Daisy
  username: admin
  password: !secret hik_pwd
