---
- platform: mqtt
  name: "Portable Fan"
  state_topic: "stat/portablefan/POWER1"
  command_topic: "cmnd/portablefan/POWER1"
  oscillation_state_topic: "stat/portablefan/POWER2"
  oscillation_command_topic: "cmnd/portablefan/POWER2"
  # speed_state_topic: "stat/portablefan/speed"
  # speed_command_topic: "cmnd/portablefan/TuyaSend4"
  qos: 0
  payload_on: 'ON'
  payload_off: 'OFF'
  payload_oscillation_on: 'ON'
  payload_oscillation_off: 'OFF'
  # payload_low_speed: '3,0'
  availability_topic: "tele/portablefan/LWT"
  payload_available: Online
  payload_not_available: Offline


  # percentage_state_topic: "stat/yourtopic/speed"
  percentage_value_template: '{{ ((value | replace("3,","")) | int + 1) * 25 }}'
  percentage_command_topic: "cmnd/yourtopic/tuyasend4"
  percentage_command_template: "3,{{ ((value | int - 1) / 25) | int }}"
  preset_mode_state_topic: "stat/yourtopic/speed"
  preset_mode_value_template: '{{ value | replace("3,0", "low") | replace("3,1", "medium") | replace("3,2", "medium-high") | replace("3,3", "high") }}'
  preset_mode_command_topic: "cmnd/yourtopic/tuyasend4"
  preset_mode_command_template: '{{ value | replace("low", "3,0") | replace("medium", "3,1") | replace("medium-high", "3,2") | replace("high", "3,3") }}'
  preset_modes:
    - "low"
    - "medium"
    - "medium-high"
    - "high"
