---
- platform: mqtt
  name: "Portable Fan"
  state_topic: "stat/portablefan/POWER1"
  command_topic: "cmnd/portablefan/POWER1"
  oscillation_state_topic: "stat/portablefan/POWER2"
  oscillation_command_topic: "cmnd/portablefan/POWER2"
  speed_state_topic: "stat/portablefan/speed"
  speed_command_topic: "cmnd/portablefan/TuyaSend4"
  qos: 0
  payload_on: 'ON'
  payload_off: 'OFF'
  payload_oscillation_on: 'ON'
  payload_oscillation_off: 'OFF'
  payload_low_speed: '3,0'
  payload_medium_speed: '3,1'
  payload_high_speed: '3,3'
  availability_topic: tele/portablefan/LWT
  payload_available: Online
  payload_not_available: Offline
  speeds:
    - low
    - medium
    - high
