---
- platform: min_max
  name: House Humidity
  round_digits: 0
  type: mean
  entity_ids:
    - sensor.aeotec_multipurpose_sensor_relative_humidity_measurement

- platform: websocket_api
- platform: season
- platform: uptime

- platform: command_line
  name: Public IP
  command: "dig +short myip.opendns.com @resolver1.opendns.com"
  scan_interval: 1800

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone2/temp"
  value_template: "{{ value | multiply(0.001) | round(2) }}"
  unit_of_measurement: "°C"
  scan_interval: 600

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: last_boot

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"
# HVAC tracking
- platform: history_stats
  name: daily hvac heat on time
  entity_id: binary_sensor.hvac_heat
  state: "on"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 24
- platform: history_stats
  name: daily hvac heat on count
  entity_id: binary_sensor.hvac_heat
  state: "on"
  type: count
  end: "{{ now() }}"
  duration:
    hours: 24

- platform: history_stats
  name: daily hvac ac on time
  entity_id: binary_sensor.hvac_ac
  state: "on"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 24
- platform: history_stats
  name: daily hvac ac on count
  entity_id: binary_sensor.hvac_ac
  state: "on"
  type: count
  end: "{{ now() }}"
  duration:
    hours: 24

- platform: history_stats
  name: daily hvac on time
  entity_id: binary_sensor.hvac
  state: "on"
  type: time
  end: "{{ now() }}"
  duration:
    hours: 24
- platform: history_stats
  name: daily hvac on count
  entity_id: binary_sensor.hvac
  state: "on"
  type: count
  end: "{{ now() }}"
  duration:
    hours: 24
- platform: history_stats
  name: daily hvac duty cycle
  entity_id: binary_sensor.hvac
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    hours: 24
# rtl_433 sensors
# - platform: mqtt
#   name: Nursery Temperature
#   state_topic: "rtl_433/Acurite-Tower/4303"
#   unit_of_measurement: "°F"
#   value_template: "{{ value_json.temperature_F }}"
# - platform: mqtt
#   name: Nursery Humidity
#   state_topic: "rtl_433/Acurite-Tower/4303"
#   unit_of_measurement: "%"
#   value_template: "{{ value_json.humidity }}"
# - platform: mqtt
#   name: Gym Temperature
#   state_topic: "rtl_433/Acurite-Tower/14641"
#   unit_of_measurement: "°F"
#   value_template: "{{ value_json.temperature_F }}"
# - platform: mqtt
#   name: Gym Humidity
#   state_topic: "rtl_433/Acurite-Tower/14641"
#   unit_of_measurement: "%"
#   value_template: "{{ value_json.humidity }}"
# - platform: mqtt
#   name: Kitchen Freezer Temperature
#   state_topic: "rtl_433/Acurite-986/15488"
#   unit_of_measurement: "°F"
#   value_template: "{{ value_json.temperature_F }}"
# - platform: mqtt
#   name: Kitchen Fridge Temperature
#   state_topic: "rtl_433/Acurite-986/37649"
#   unit_of_measurement: "°F"
#   value_template: "{{ value_json.temperature_F }}"
# - platform: mqtt
#   name: Bar Freezer Temperature
#   state_topic: "rtl_433/Acurite-986/50597"
#   unit_of_measurement: "°F"
#   value_template: "{{ value_json.temperature_F }}"
# - platform: mqtt
#   name: Bar Fridge Temperature
#   state_topic: "rtl_433/Acurite-986/17933"
#   unit_of_measurement: "°F"
#   value_template: "{{ value_json.temperature_F }}"

# rtl_915 sensors
# - platform: mqtt
#   name: Water Meter
#   state_topic: "rtl_915/SCM_/68242959"
#   unit_of_measurement: "Gallons"
#   value_template: "{{ value_json.Consumption }}"
# - platform: mqtt
#   name: Gas Meter
#   state_topic: "rtl_915/ERT-SCM/48150945"
#   unit_of_measurement: "M3"
#   value_template: "{{ value_json.consumption_data }}"

#THERMOSTAT TEMPLATES
# main_status:
#   friendly_name: Main Floor Status
#   value_template: >-
#     {{ state_attr('climate.main_floor', 'current_temperature') | round | int }}° / {{ state_attr('climate.main_floor', 'current_humidity') | round | int }}% humidity
# upstairs_status:
#   friendly_name: Upstairs Status
#   value_template: >-
#     {{ state_attr('climate.upstairs', 'current_temperature') | round | int }}° / {{ state_attr('climate.upstairs', 'current_humidity') | round | int }}% humidity
# familyroom_temperature:
#   friendly_name: Family Room Temperature
#   value_template: >-
#     {{ states('sensor.family_room_temperature') | round | int }}°
# diningroom_temperature:
#   friendly_name: Dining Room Temperature
#   value_template: >-
#     {{ states('sensor.dining_room_temperature') | round | int }}°
