---
- platform: min_max
  name: House Humidity
  round_digits: 0
  type: mean
  entity_ids:
    - sensor.lounge_pir_humidity
    - sensor.hvac_humidity

- platform: websocket_api

- platform: rest
  name: WireGuard peers status API
  resource: "http://a0d7b954-wireguard"
  value_template: "OK"
  json_attributes:
    - macbook
    - jons-phone

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: last_boot

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"
