---
# fully kiosk
- platform: command_line
  switches:
    basement_tablet_screen:
      command_on: !secret basement_tablet_screen_on
      command_off: !secret basement_tablet_screen_off
      command_state: !secret basement_tablet_screen_state
      value_template: "{{ value == 'on' }}"
      friendly_name: basement tablet screen
