---
- platform: circadian_lighting
  name: Master
  min_brightness: 20
  lights_ct:
    - light.master_entry_lifx
    - light.sitting_room_lifx
    - light.lauras_lamp_lifx
    - light.jons_lamp_lifx
- platform: circadian_lighting
  name: Master Bath
  min_brightness: 30
  lights_ct:
    - light.master_bath_toekick
    - light.master_toilet_fixture
- platform: circadian_lighting
  name: Gym
  min_brightness: 5
  max_brightness: 90
  lights_ct:
    - light.gym_cans
- platform: circadian_lighting
  name: Office
  max_brightness: 90
  lights_ct:
    - light.office_cans

# fully kiosk
- platform: command_line
  switches:
    basement_tablet_screen:
      command_on: !secret basement_tablet_screen_on
      command_off: !secret basement_tablet_screen_off
      command_state: !secret basement_tablet_screen_state
      value_template: "{{ value == 'on' }}"
      friendly_name: basement tablet screen
