---
esphome:
  name: esp_master_sitting_chair
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "iot"
  password: !secret iot_pw
  fast_connect: true
  reboot_timeout: 45min
  power_save_mode: none

captive_portal:

logger:
  level: ERROR

mqtt:
  broker: !secret hass_ip
  username: !secret mqtt_user
  password: !secret mqtt_pass

ota:
  password: !secret esp_ota

sensor:
  - platform: hx711
    name: "Master Sitting Chair"
    dout_pin: D0
    clk_pin: D1
    gain: 128
    update_interval: 10s
