---
esphome:
  name: esp_garage_cars
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "iot"
  password: !secret iot_pw
  fast_connect: true
  reboot_timeout: 45min
  # manual_ip:
  #   static_ip: 192.168.45.203
  #   gateway: 192.168.45.1
  #   subnet: 255.255.255.0

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:
  password: !secret hass_api

ota:
  password: !secret esp_ota

sensor:
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    name: "Jons Car"
    update_interval: 60s
#    update_interval: 100ms
    filters:
      - delta: 0.10
#    filters:
#      - filter_out: nan
#      - lambda: return (3-x)/3*100;
