---
esphome:
  name: esp_master_sitting
  platform: ESP8266
  board: nodemcuv2

  on_loop:
    then:
      - lambda: delay(5);

wifi:
  ssid: "iot"
  password: !secret iot_pw
  fast_connect: true
  reboot_timeout: 45min
  power_save_mode: none
  # manual_ip:
  #   static_ip: 192.168.45.209
  #   gateway: 192.168.45.1
  #   subnet: 255.255.255.0

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:
  password: !secret hass_api

ota:
  password: !secret esp_ota

sensor:
  - platform: adc
    pin: A0
    name: "Sitting Room Lux"
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Sitting Room PIR"
    device_class: motion
