---
esphome:
  name: esp_office_desk
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "iot"
  password: !secret iot_pw
  fast_connect: true
  reboot_timeout: 45min

# Enable logging
logger:
  level: ERROR

mqtt:
  broker: !secret hass_ip
  username: !secret mqtt_user
  password: !secret mqtt_pass

ota:
  password: !secret esp_ota

sensor:
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    name: "Office Desk"
    update_interval: 60s
#    update_interval: 100ms
    filters:
      - delta: 0.10
#    filters:
#      - filter_out: nan
#      - lambda: return (3-x)/3*100;
