---
esphome:
  name: esp_master_entry
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "iot"
  password: !secret iot_pw
  manual_ip:
    static_ip: 192.168.45.207
    gateway: 192.168.45.1
    subnet: 255.255.255.0

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:
  password: !secret hass_api

ota:
  password: !secret esp_ota

sensor:
  - platform: dht
    model: DHT22
    pin: D7
    temperature:
      name: "temperature"
    humidity:
      name: "humidity"

binary_sensor:
  - platform: gpio
    pin: D5
    name: "PIR"
    device_class: motion
