---
esphome:
  name: switch1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "iot"
  fast_connect: true
  reboot_timeout: 45min
  password: !secret iot_pw

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:
  password: !secret hass_api

ota:
  password: !secret esp_ota

switch:
  - platform: gpio
    name: "Office Speakers"
    pin: GPIO12
    id: relay
