---
homeassistant:
  whitelist_external_dirs:
    - /config/www

camera:
  - platform: mjpeg
    name: driveway_hist
    mjpeg_url: !secret frigate_driveway_cam
  - platform: local_file
    name: driveway_history1
    file_path: /config/www/driveway_image1.jpg
  - platform: local_file
    name: driveway_history2
    file_path: /config/www/driveway_image2.jpg
  - platform: local_file
    name: driveway_history3
    file_path: /config/www/driveway_image3.jpg
  - platform: local_file
    name: driveway_history4
    file_path: /config/www/driveway_image4.jpg
  - platform: local_file
    name: driveway_history5
    file_path: /config/www/driveway_image5.jpg

automation:
  - alias: create_history_driveway
    trigger:
      - entity_id: binary_sensor.driveway_person
        from: "off"
        platform: state
        to: "on"
    action:
      - data:
          entity_id: camera.driveway_history2
          filename: /config/www/driveway_image1.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.driveway_history3
          filename: /config/www/driveway_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.driveway_history4
          filename: /config/www/driveway_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.driveway_history5
          filename: /config/www/driveway_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.driveway_hist
          filename: /config/www/driveway_image5.jpg
        service: camera.snapshot

script:
  setup_frigate_history_driveway:
    sequence:
      - data:
          entity_id: camera.driveway_hist
          filename: /config/www/driveway_image5.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.driveway_hist
          filename: /config/www/driveway_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.driveway_hist
          filename: /config/www/driveway_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.driveway_hist
          filename: /config/www/driveway_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.driveway_hist
          filename: /config/www/driveway_image1.jpg
        service: camera.snapshot
