---
homeassistant:
  whitelist_external_dirs:
    - /config/www

camera:
  - platform: mjpeg
    name: garage_hist
    mjpeg_url: !secret frigate_garage_cam
  - platform: local_file
    name: garage_history1
    file_path: /config/www/garage_image1.jpg
  - platform: local_file
    name: garage_history2
    file_path: /config/www/garage_image2.jpg
  - platform: local_file
    name: garage_history3
    file_path: /config/www/garage_image3.jpg
  - platform: local_file
    name: garage_history4
    file_path: /config/www/garage_image4.jpg
  - platform: local_file
    name: garage_history5
    file_path: /config/www/garage_image5.jpg

automation:
  - alias: create_history_garage
    trigger:
      - entity_id: binary_sensor.garage_person
        from: "off"
        platform: state
        to: "on"
    action:
      - data:
          entity_id: camera.garage_history2
          filename: /config/www/garage_image1.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history3
          filename: /config/www/garage_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history4
          filename: /config/www/garage_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history5
          filename: /config/www/garage_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image5.jpg
        service: camera.snapshot

script:
  setup_frigate_history_garage:
    sequence:
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image5.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image1.jpg
        service: camera.snapshot
