---
homeassistant:
  whitelist_external_dirs:
    - /config/www

camera:
  - platform: mjpeg
    name: deck_hist
    mjpeg_url: !secret frigate_deck_cam
  - platform: local_file
    name: deck_history1
    file_path: /config/www/deck_image1.jpg
  - platform: local_file
    name: deck_history2
    file_path: /config/www/deck_image2.jpg
  - platform: local_file
    name: deck_history3
    file_path: /config/www/deck_image3.jpg
  - platform: local_file
    name: deck_history4
    file_path: /config/www/deck_image4.jpg
  - platform: local_file
    name: deck_history5
    file_path: /config/www/deck_image5.jpg

automation:
  - alias: create_history_deck
    trigger:
      - entity_id: binary_sensor.deck_person
        from: "off"
        platform: state
        to: "on"
    action:
      - data:
          entity_id: camera.deck_history2
          filename: /config/www/deck_image1.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_history3
          filename: /config/www/deck_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_history4
          filename: /config/www/deck_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_history5
          filename: /config/www/deck_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_hist
          filename: /config/www/deck_image5.jpg
        service: camera.snapshot

script:
  setup_frigate_history_deck:
    sequence:
      - data:
          entity_id: camera.deck_hist
          filename: /config/www/deck_image5.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_hist
          filename: /config/www/deck_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_hist
          filename: /config/www/deck_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_hist
          filename: /config/www/deck_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_hist
          filename: /config/www/deck_image1.jpg
        service: camera.snapshot
