---
camera:
  - platform: mjpeg
    name: kitchen_hist
    mjpeg_url: !secret kitchenwyze_cam
  - platform: local_file
    name: kitchen_history1
    file_path: /config/www/kitchen_image1.jpg
  - platform: local_file
    name: kitchen_history2
    file_path: /config/www/kitchen_image2.jpg
  - platform: local_file
    name: kitchen_history3
    file_path: /config/www/kitchen_image3.jpg
  - platform: local_file
    name: kitchen_history4
    file_path: /config/www/kitchen_image4.jpg
  - platform: local_file
    name: kitchen_history5
    file_path: /config/www/kitchen_image5.jpg
  - platform: local_file
    name: kitchen_history6
    file_path: /config/www/kitchen_image6.jpg
  - platform: local_file
    name: kitchen_history7
    file_path: /config/www/kitchen_image7.jpg
  - platform: local_file
    name: kitchen_history8
    file_path: /config/www/kitchen_image8.jpg
  - platform: local_file
    name: kitchen_history9
    file_path: /config/www/kitchen_image9.jpg
  - platform: local_file
    name: kitchen_history10
    file_path: /config/www/kitchen_image10.jpg

automation:
  - alias: create_history_kitchen
    trigger:
      - entity_id: binary_sensor.kitchen_person
        from: "off"
        platform: state
        to: "on"
    action:
      - data:
          entity_id: camera.kitchen_history2
          filename: /config/www/kitchen_image1.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_history3
          filename: /config/www/kitchen_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_history4
          filename: /config/www/kitchen_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_history5
          filename: /config/www/kitchen_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_history6
          filename: /config/www/kitchen_image5.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_history7
          filename: /config/www/kitchen_image6.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_history8
          filename: /config/www/kitchen_image7.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_history9
          filename: /config/www/kitchen_image8.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_history10
          filename: /config/www/kitchen_image9.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image10.jpg
        service: camera.snapshot

script:
  setup_frigate_history_kitchen:
    sequence:
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image10.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image9.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image8.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image7.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image6.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image5.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.kitchen_hist
          filename: /config/www/kitchen_image1.jpg
        service: camera.snapshot
