---
camera:
  - platform: mjpeg
    name: garage_hist
    mjpeg_url: !secret frigate_garage_cam
  - platform: local_file
    name: garage_history1
    file_path: /config/www/garage_image1.jpg
  - platform: local_file
    name: garage_history2
    file_path: /config/www/garage_image2.jpg
  - platform: local_file
    name: garage_history3
    file_path: /config/www/garage_image3.jpg
  - platform: local_file
    name: garage_history4
    file_path: /config/www/garage_image4.jpg
  - platform: local_file
    name: garage_history5
    file_path: /config/www/garage_image5.jpg
  - platform: local_file
    name: garage_history6
    file_path: /config/www/garage_image6.jpg
  - platform: local_file
    name: garage_history7
    file_path: /config/www/garage_image7.jpg
  - platform: local_file
    name: garage_history8
    file_path: /config/www/garage_image8.jpg
  - platform: local_file
    name: garage_history9
    file_path: /config/www/garage_image9.jpg
  - platform: local_file
    name: garage_history10
    file_path: /config/www/garage_image10.jpg

automation:
  - alias: create_history_garage
    trigger:
      - entity_id: binary_sensor.garage_person
        from: "off"
        platform: state
        to: "on"
    action:
      - data:
          entity_id: camera.garage_history2
          filename: /config/www/garage_image1.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history3
          filename: /config/www/garage_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history4
          filename: /config/www/garage_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history5
          filename: /config/www/garage_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history6
          filename: /config/www/garage_image5.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history7
          filename: /config/www/garage_image6.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history8
          filename: /config/www/garage_image7.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history9
          filename: /config/www/garage_image8.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_history10
          filename: /config/www/garage_image9.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image10.jpg
        service: camera.snapshot

script:
  setup_frigate_history_garage:
    sequence:
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image10.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image9.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image8.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image7.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image6.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image5.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.garage_hist
          filename: /config/www/garage_image1.jpg
        service: camera.snapshot
