---
camera:
  - platform: mjpeg
    name: deck_stairs_hist
    mjpeg_url: !secret frigate_deck_stairs_cam
  - platform: local_file
    name: deck_stairs_history1
    file_path: /config/www/deck_stairs_image1.jpg
  - platform: local_file
    name: deck_stairs_history2
    file_path: /config/www/deck_stairs_image2.jpg
  - platform: local_file
    name: deck_stairs_history3
    file_path: /config/www/deck_stairs_image3.jpg
  - platform: local_file
    name: deck_stairs_history4
    file_path: /config/www/deck_stairs_image4.jpg
  - platform: local_file
    name: deck_stairs_history5
    file_path: /config/www/deck_stairs_image5.jpg
  - platform: local_file
    name: deck_stairs_history6
    file_path: /config/www/deck_stairs_image6.jpg
  - platform: local_file
    name: deck_stairs_history7
    file_path: /config/www/deck_stairs_image7.jpg
  - platform: local_file
    name: deck_stairs_history8
    file_path: /config/www/deck_stairs_image8.jpg
  - platform: local_file
    name: deck_stairs_history9
    file_path: /config/www/deck_stairs_image9.jpg
  - platform: local_file
    name: deck_stairs_history10
    file_path: /config/www/deck_stairs_image10.jpg

automation:
  - alias: create_history_deck_stairs
    trigger:
      - entity_id: binary_sensor.deck_stairs_person
        from: "off"
        platform: state
        to: "on"
    action:
      - data:
          entity_id: camera.deck_stairs_history2
          filename: /config/www/deck_stairs_image1.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_history3
          filename: /config/www/deck_stairs_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_history4
          filename: /config/www/deck_stairs_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_history5
          filename: /config/www/deck_stairs_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_history6
          filename: /config/www/deck_stairs_image5.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_history7
          filename: /config/www/deck_stairs_image6.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_history8
          filename: /config/www/deck_stairs_image7.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_history9
          filename: /config/www/deck_stairs_image8.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_history10
          filename: /config/www/deck_stairs_image9.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image10.jpg
        service: camera.snapshot

script:
  setup_frigate_history_deck_stairs:
    sequence:
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image10.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image9.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image8.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image7.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image6.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image5.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.deck_stairs_hist
          filename: /config/www/deck_stairs_image1.jpg
        service: camera.snapshot
