---
name: Home Assistant CI
on:
  push:
  pull_request:
  schedule:
    - cron: 0 9 * * 0

jobs:
  secret_check:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@master
      - name: gitleaks-action
        # uses: eshork/gitleaks-action@v1.0.0
        uses: eshork/gitleaks-action@master
      # - name: Secret Scan
      #   uses: max/secret-scan@1.0.0
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master

  remarklint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@master
      - name: Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@master
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint -c ./.github/yamllint.cfg .
  # ha_check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Getting your configuration from GitHub
  #       uses: actions/checkout@v1
  #     - name: Setup fake secrets.yaml
  #       run: mv ./fake_secrets.yaml ./secrets.yaml
  #     - name: Home Assistant Configuration Check
  #       uses: ludeeus/action-ha-config-check@0.0.1
  #       env:
  #         ACTION_VERSION: STABLE
  #         ACTION_CONFIG_PATH: ./
